package com.pcis.schema.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * Base class for PCIS entities whose primary key is an internal surrogate generated by
 * {@code GENERATED ALWAYS AS IDENTITY} (PostgreSQL) or {@code IDENTITY} (SQL Server / Db2).
 *
 * <p>These keys are never surfaced to end users or external systems, so they carry no
 * parallel-run collision risk with the legacy Db2 for i sequences.
 *
 * <p>Concrete subclasses must override the column name via {@code @AttributeOverride}:
 * <pre>{@code
 * @Entity
 * @Table(name = "APPROVAL_T")
 * @AttributeOverride(name = "id", column = @Column(name = "APPROVAL_ID"))
 * public class ApprovalEntity extends IdentityKeyEntity { ... }
 * }</pre>
 *
 * @see <a href="docs/key-generation-strategy.md">Key Generation Strategy</a>
 */
@MappedSuperclass
public abstract class IdentityKeyEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", insertable = false, updatable = false)
    private Long id;

    public Long getId() {
        return id;
    }
}
