replicaCount: 0
autoscaling:
  enabled: false
  enableHpa: false
podDisruptionBudget:
  enabled: false
  enablePdb: false
ingress:
  enabled: false
  host: ''
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
env:
  SPRING_PROFILES_ACTIVE: dev
  DATABASE_URL: jdbc:postgresql://postgresql.pcis-dev.svc.cluster.local:5432/pcis_sync
  DATABASE_USERNAME: pcis
  DATABASE_PASSWORD: pcis
  PCIS_SYNC_ENABLED: 'false'
image:
  repository: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/pcis-sync-agent
  tag: dev-0d175ae-20260812173903-amd64
  pullPolicy: Always
