-- WO-197: align claims outbox to pcis-outbox standard schema
DROP TABLE IF EXISTS outbox_events;

CREATE TABLE outbox_events (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    AGGREGATE_TYPE VARCHAR(100) NOT NULL,
    AGGREGATE_ID VARCHAR(100) NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    PAYLOAD JSONB NOT NULL,
    IDEMPOTENCY_KEY UUID NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT TIMESTAMP,
    LAST_ERROR VARCHAR(500),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT uq_outbox_idempotency UNIQUE (IDEMPOTENCY_KEY)
);

CREATE INDEX IF NOT EXISTS idx_outbox_relay
    ON outbox_events (STATUS, NEXT_ATTEMPT_AT) WHERE STATUS = 'PENDING';
