{{- range .Values.jobs }}
{{- if .serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name | default .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "pcis-batch.labels" $ | nindent 4 }}
    pcis.batch/job: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
  {{- with .serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
