-- Batch run log table for CLM006B job instrumentation
CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
    RUN_LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PGM_NAME VARCHAR(10) NOT NULL,
    RUN_DATE DATE NOT NULL,
    REC_SELECTED INTEGER NOT NULL DEFAULT 0,
    REC_UPDATED INTEGER NOT NULL DEFAULT 0,
    REC_ERRORS INTEGER NOT NULL DEFAULT 0,
    REC_DELINQUENT INTEGER,
    START_TIMESTAMP TIMESTAMP(6) NOT NULL,
    END_TIMESTAMP TIMESTAMP(6) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);
