-- V1 premium-svc rating schema (WO-186)

CREATE TABLE IF NOT EXISTS RATE_TABLE_T (
    RATE_TABLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POLICY_TYPE CHAR(4) NOT NULL,
    TERRITORY CHAR(3) NOT NULL,
    BASE_RATE NUMERIC(9,2) NOT NULL,
    EFF_DATE DATE NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RATE_FACTOR_T (
    RATE_FACTOR_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RATE_TABLE_ID BIGINT NOT NULL REFERENCES RATE_TABLE_T (RATE_TABLE_ID),
    FACTOR_CODE VARCHAR(20) NOT NULL,
    FACTOR_VALUE NUMERIC(7,4) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RISK_SCORE_FACTOR_T (
    RISK_FACTOR_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FACTOR_CODE VARCHAR(20) NOT NULL,
    FACTOR_WEIGHT NUMERIC(7,4) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UW_RULE_T (
    UW_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_CODE VARCHAR(20) NOT NULL,
    RULE_TEXT VARCHAR(200) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DISCOUNT_RULE_T (
    DISC_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DISC_CODE VARCHAR(20) NOT NULL,
    DISC_PCT NUMERIC(7,4) NOT NULL,
    EFF_DATE DATE NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SURCHARGE_RULE_T (
    SURCH_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SURCH_CODE VARCHAR(20) NOT NULL,
    SURCH_PCT NUMERIC(7,4) NOT NULL,
    EFF_DATE DATE NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TAX_TABLE_T (
    TAX_TABLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATE CHAR(2) NOT NULL,
    TAX_PCT NUMERIC(7,4) NOT NULL,
    EFF_DATE DATE NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PREMIUM_CALC_T (
    CALC_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POL_NBR VARCHAR(12),
    FINAL_PREMIUM NUMERIC(11,2),
    CALC_DATE DATE,
    SNAPSHOT_ID VARCHAR(36),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PREMIUM_CALC_DETAIL_T (
    DETAIL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CALC_ID BIGINT NOT NULL REFERENCES PREMIUM_CALC_T (CALC_ID),
    COMPONENT VARCHAR(30) NOT NULL,
    COMPONENT_AMT NUMERIC(11,2) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UW_REFERRAL_T (
    REFERRAL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CALC_ID BIGINT REFERENCES PREMIUM_CALC_T (CALC_ID),
    RULE_ID BIGINT,
    THRESHOLD_AMT NUMERIC(11,2),
    STATUS CHAR(4) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rate_factor_rate_table_id ON RATE_FACTOR_T (RATE_TABLE_ID);
