-- Rating pipeline extensions (WO-189)

ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS policy_type CHAR(4);
ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS stacking_group VARCHAR(20);
ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) DEFAULT 'MULTIPLICATIVE';
ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS discount_amt NUMERIC(11,2);
ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS max_combined_pct NUMERIC(5,4);
ALTER TABLE discount_rule_t ADD COLUMN IF NOT EXISTS eligibility_code VARCHAR(20);

ALTER TABLE surcharge_rule_t ADD COLUMN IF NOT EXISTS policy_type CHAR(4);
ALTER TABLE surcharge_rule_t ADD COLUMN IF NOT EXISTS surcharge_type VARCHAR(20) DEFAULT 'MANDATORY';
ALTER TABLE surcharge_rule_t ADD COLUMN IF NOT EXISTS calc_type VARCHAR(20) DEFAULT 'MULTIPLICATIVE';
ALTER TABLE surcharge_rule_t ADD COLUMN IF NOT EXISTS surcharge_amt NUMERIC(11,2);
ALTER TABLE surcharge_rule_t ADD COLUMN IF NOT EXISTS max_combined_surcharge_pct NUMERIC(5,4);

ALTER TABLE tax_table_t ADD COLUMN IF NOT EXISTS tax_type VARCHAR(20);
ALTER TABLE tax_table_t ADD COLUMN IF NOT EXISTS flat_fee NUMERIC(11,2) DEFAULT 0;
ALTER TABLE tax_table_t ADD COLUMN IF NOT EXISTS compound_flag BOOLEAN DEFAULT FALSE;
ALTER TABLE tax_table_t ADD COLUMN IF NOT EXISTS calc_sequence INTEGER DEFAULT 1;

ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS policy_type CHAR(4);
ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS rule_type VARCHAR(20);
ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS condition_field VARCHAR(30);
ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS condition_operator VARCHAR(10);
ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS condition_value NUMERIC(11,2);
ALTER TABLE uw_rule_t ADD COLUMN IF NOT EXISTS outcome VARCHAR(10);

CREATE TABLE IF NOT EXISTS outbox_events (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AGGREGATE_TYPE VARCHAR(100) NOT NULL,
    AGGREGATE_ID VARCHAR(100) NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    PAYLOAD JSONB NOT NULL,
    IDEMPOTENCY_KEY UUID NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT TIMESTAMP,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_premium_calc_snapshot ON premium_calc_t (snapshot_id);
