-- PCIS Cross-Service Integration Fixtures (WO-287/288/289)
-- Deterministic customer -> policy -> claim -> billing chain for contract and integration tests.
-- Idempotent: scoped deletes and upserts keyed by CROSS9* identifiers.

DELETE FROM CLAIM_T WHERE CLAIM_ID = 'CLM900000001';
DELETE FROM BILLING_SCHEDULE_T WHERE POL_NBR = 'POL900000001';
DELETE FROM BILLING_PLAN_T WHERE POL_NBR = 'POL900000001';
DELETE FROM POLICY_T WHERE POL_NBR = 'POL900000001';
DELETE FROM CUSTOMER_T WHERE CUST_ID = 'CUST900001';
DELETE FROM AGENT_LICENSE_T WHERE AGT_ID = 'AGT90001';
DELETE FROM AGENT_T WHERE AGT_ID = 'AGT90001';

INSERT INTO AGENT_T (AGT_ID, AGT_NAME, AGT_STATUS, AGT_TYPE, HIRE_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('AGT90001', 'Cross Service Agent', 'ACTIVE', 'IND', DATE '2019-01-01', 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP)
ON CONFLICT (AGT_ID) DO UPDATE SET
    AGT_NAME = EXCLUDED.AGT_NAME,
    AGT_STATUS = EXCLUDED.AGT_STATUS,
    UPD_USER = EXCLUDED.UPD_USER,
    UPD_TIMESTAMP = EXCLUDED.UPD_TIMESTAMP;

INSERT INTO AGENT_LICENSE_T (AGT_ID, STATE, LICENSE_NBR, EXPIRY_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
SELECT 'AGT90001', 'NY', 'LIC900001', DATE '2028-12-31', 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM AGENT_LICENSE_T WHERE AGT_ID = 'AGT90001' AND STATE = 'NY'
);

INSERT INTO CUSTOMER_T (
    CUST_ID, CUST_TYPE, CUST_NAME, FIRST_NAME, LAST_NAME, TAX_ID, DOB, EMAIL, PHONE,
    CUST_STATUS, ASSIGNED_AGENT, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP,
    CUST_GENDER, CUST_MARITAL_ST, CUST_CREDIT_SCORE)
VALUES
    ('CUST900001', 'I', 'Cross Service Customer', 'Cross', 'Service', '900900001', DATE '1980-04-04',
     'cross.service@test.pcis', '5559000001', 'ACTIVE', 'AGT90001', 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP,
     'M', 'M', 700)
ON CONFLICT (CUST_ID) DO UPDATE SET
    CUST_NAME = EXCLUDED.CUST_NAME,
    EMAIL = EXCLUDED.EMAIL,
    UPD_USER = EXCLUDED.UPD_USER,
    UPD_TIMESTAMP = EXCLUDED.UPD_TIMESTAMP;

INSERT INTO POLICY_T (
    POL_NBR, CUST_ID, AGT_ID, POLICY_TYPE, POL_STATUS, EFF_DATE, EXP_DATE,
    PREM_ANNUAL, BILL_FREQ, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('POL900000001', 'CUST900001', 'AGT90001', 'AUTO', 'ACTV', DATE '2025-01-01', DATE '2026-01-01',
     CAST(1500.00 AS NUMERIC(13,2)), 'M', 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP)
ON CONFLICT (POL_NBR) DO UPDATE SET
    PREM_ANNUAL = EXCLUDED.PREM_ANNUAL,
    POL_STATUS = EXCLUDED.POL_STATUS,
    UPD_USER = EXCLUDED.UPD_USER,
    UPD_TIMESTAMP = EXCLUDED.UPD_TIMESTAMP;

INSERT INTO BILLING_PLAN_T (POL_NBR, BILL_FREQ, INSTALLMENT_CNT, PLAN_STATUS, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
SELECT 'POL900000001', 'M', 12, 'ACTV', 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BILLING_PLAN_T WHERE POL_NBR = 'POL900000001');

INSERT INTO BILLING_SCHEDULE_T (
    POL_NBR, BILL_PLAN_ID, INSTALLMENT_NBR, DUE_DATE, AMT_DUE, AMT_PAID, SCHED_STATUS,
    CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP, COMM_CALC_FLAG)
SELECT 'POL900000001',
       bp.bill_plan_id,
       1,
       DATE '2025-02-01',
       CAST(125.00 AS NUMERIC(11,2)),
       CAST(0.00 AS NUMERIC(11,2)),
       'O',
       'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP, 'N'
FROM BILLING_PLAN_T bp
WHERE bp.pol_nbr = 'POL900000001'
  AND NOT EXISTS (
      SELECT 1 FROM BILLING_SCHEDULE_T bs
      WHERE bs.pol_nbr = 'POL900000001' AND bs.installment_nbr = 1
  );

INSERT INTO CLAIM_T (CLAIM_ID, POL_NBR, CUST_ID, CLAIM_STATUS, LOSS_DATE, PAID_TO_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('CLM900000001', 'POL900000001', 'CUST900001', 'OPEN', DATE '2025-03-01', CAST(0.00 AS NUMERIC(13,2)), 'CROSSFX', CURRENT_TIMESTAMP, 'CROSSFX', CURRENT_TIMESTAMP)
ON CONFLICT (CLAIM_ID) DO UPDATE SET
    CLAIM_STATUS = EXCLUDED.CLAIM_STATUS,
    UPD_USER = EXCLUDED.UPD_USER,
    UPD_TIMESTAMP = EXCLUDED.UPD_TIMESTAMP;
