-- PCIS V1 Baseline Schema (WO-149)
-- Authority: Property_Casualty_Insurance_System/PCIS_Database_Design.md
-- PostgreSQL 17 compatible DDL

-- Sequence objects (business document keys)

CREATE SEQUENCE SEQ_CUSTOMER_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_AGENT_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_QUOTE_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_POLICY_NBR START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_COVERAGE_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_CLAIM_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_ADJUSTER_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_TREATY_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_COMMISSION_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_AUDIT_LOG_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_INVOICE_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_REFUND_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_DOCUMENT_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;
CREATE SEQUENCE SEQ_LEDGER_ID START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;

-- AGENT_COMMISSION_T (domain: AGT)
CREATE TABLE AGENT_COMMISSION_T (
    AGT_COMM_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    AGT_ID VARCHAR(8),
    POL_NBR VARCHAR(12),
    COMM_AMT NUMERIC(11,2),
    COMM_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (AGT_COMM_ID)
);

-- AGENT_LICENSE_T (domain: AGT)
CREATE TABLE AGENT_LICENSE_T (
    LICENSE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    AGT_ID VARCHAR(8),
    STATE CHAR(2),
    LICENSE_NBR VARCHAR(20),
    EXPIRY_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (LICENSE_ID)
);

-- AGENT_T (domain: AGT)
CREATE TABLE AGENT_T (
    AGT_ID VARCHAR(8),
    AGT_NAME VARCHAR(60),
    AGT_STATUS CHAR(10),
    AGT_TYPE CHAR(4),
    HIRE_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (AGT_ID)
);

-- APPROVAL_T (domain: CLM)
CREATE TABLE APPROVAL_T (
    APPROVAL_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    APPROVER_ID VARCHAR(10),
    APPROVED_AMT NUMERIC(13,2),
    APPROVAL_STATUS CHAR(10),
    APPROVAL_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    RESERVE_HIST_ID BIGINT,
    PRIMARY KEY (APPROVAL_ID)
);

-- AUDIT_LOG_ARCHIVE_T (domain: AUD)
CREATE TABLE AUDIT_LOG_ARCHIVE_T (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    PROGRAM_NAME VARCHAR(10),
    ACTION_CODE VARCHAR(10),
    TABLE_NAME VARCHAR(30),
    RECORD_KEY VARCHAR(40),
    USER_ID VARCHAR(10),
    LOG_TIMESTAMP TIMESTAMP,
    ARCHIVE_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (LOG_ID)
);

-- BILLING_NOTICE_T (domain: BIL)
CREATE TABLE BILLING_NOTICE_T (
    NOTICE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    BILL_SCHED_ID BIGINT,
    CUST_ID VARCHAR(10),
    NOTICE_DATE DATE,
    AMOUNT_DUE NUMERIC(11,2),
    DELIVERY_EMAIL VARCHAR(100),
    NOTICE_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (NOTICE_ID)
);

-- BILLING_PLAN_T (domain: BIL)
CREATE TABLE BILLING_PLAN_T (
    BILL_PLAN_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    BILL_FREQ CHAR(1),
    INSTALLMENT_CNT INTEGER,
    PLAN_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (BILL_PLAN_ID)
);

-- BILLING_SCHEDULE_T (domain: BIL)
CREATE TABLE BILLING_SCHEDULE_T (
    BILL_SCHED_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12) NOT NULL,
    BILL_PLAN_ID BIGINT NOT NULL,
    INSTALLMENT_NBR INTEGER NOT NULL,
    DUE_DATE DATE NOT NULL,
    AMT_DUE NUMERIC(11,2) NOT NULL,
    AMT_PAID NUMERIC(11,2),
    SCHED_STATUS CHAR(1) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    COMM_CALC_FLAG CHAR(1),
    PRIMARY KEY (BILL_SCHED_ID)
);

-- CANCELLATION_REASON_T (domain: POL)
CREATE TABLE CANCELLATION_REASON_T (
    CANCEL_REASON CHAR(4),
    REASON_DESC VARCHAR(60),
    REFUND_ELIGIBLE CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CANCEL_REASON)
);

-- CLAIM_ADJUSTER_T (domain: CLM)
CREATE TABLE CLAIM_ADJUSTER_T (
    ADJUSTER_ID VARCHAR(10),
    ADJ_NAME VARCHAR(60),
    AUTHORITY_LIMIT NUMERIC(13,2),
    ADJ_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ADJUSTER_ID)
);

-- CLAIM_DOCUMENT_T (domain: CLM)
CREATE TABLE CLAIM_DOCUMENT_T (
    DOC_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    DOC_TYPE CHAR(10),
    DOC_PATH VARCHAR(200),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DOC_ID)
);

-- CLAIM_NOTE_T (domain: CLM)
CREATE TABLE CLAIM_NOTE_T (
    NOTE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    NOTE_TEXT VARCHAR(500),
    NOTE_USER VARCHAR(10),
    NOTE_DATE TIMESTAMP,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (NOTE_ID)
);

-- CLAIM_PAYMENT_T (domain: CLM)
CREATE TABLE CLAIM_PAYMENT_T (
    PAYMENT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    ADJUSTER_ID VARCHAR(10),
    PAYMENT_AMT NUMERIC(11,2),
    PAYMENT_DATE DATE,
    PAYEE_NAME VARCHAR(60),
    PAYMENT_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PAYMENT_ID)
);

-- CLAIM_RESERVE_HISTORY_T (domain: CLM)
CREATE TABLE CLAIM_RESERVE_HISTORY_T (
    RES_HIST_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    OLD_AMT NUMERIC(13,2),
    NEW_AMT NUMERIC(13,2),
    CHANGE_REASON VARCHAR(60),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RES_HIST_ID)
);

-- CLAIM_RESERVE_T (domain: CLM)
CREATE TABLE CLAIM_RESERVE_T (
    RESERVE_HIST_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12) NOT NULL,
    RESERVE_AMT NUMERIC(13,2) NOT NULL,
    CHANGE_REASON VARCHAR(60),
    RESERVE_STATUS CHAR(2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PAID_TO_DATE NUMERIC(13,2),
    PRIMARY KEY (RESERVE_HIST_ID)
);

-- CLAIM_T (domain: CLM)
CREATE TABLE CLAIM_T (
    CLAIM_ID VARCHAR(12),
    POL_NBR VARCHAR(12),
    CUST_ID VARCHAR(10),
    CLAIM_STATUS CHAR(4),
    LOSS_DATE DATE,
    PAID_TO_DATE NUMERIC(13,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CLAIM_ID)
);

-- CODE_TABLE_T (domain: SEC)
CREATE TABLE CODE_TABLE_T (
    CODE_TYPE VARCHAR(20),
    CODE_VALUE VARCHAR(20),
    CODE_DESC VARCHAR(60),
    ACTIVE_FLAG CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CODE_TYPE, CODE_VALUE)
);

-- COMMISSION_RATE_T (domain: AGT)
CREATE TABLE COMMISSION_RATE_T (
    RATE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POLICY_TYPE CHAR(4),
    COMM_RATE NUMERIC(7,4),
    EFF_DATE DATE,
    END_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RATE_ID)
);

-- COMMISSION_T (domain: AGT)
CREATE TABLE COMMISSION_T (
    COMMISSION_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    AGT_ID VARCHAR(8),
    POL_NBR VARCHAR(12),
    COMMISSION_AMT NUMERIC(11,2),
    CALC_DATE DATE,
    COMM_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (COMMISSION_ID)
);

-- COVERAGE_T (domain: POL)
CREATE TABLE COVERAGE_T (
    COVERAGE_ID VARCHAR(14),
    POL_NBR VARCHAR(12),
    COV_TYPE CHAR(4),
    LIMIT_AMT NUMERIC(13,2),
    DED_AMT NUMERIC(11,2),
    COV_PREMIUM NUMERIC(13,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (COVERAGE_ID)
);

-- COVERAGE_TYPE_T (domain: POL)
CREATE TABLE COVERAGE_TYPE_T (
    COV_TYPE CHAR(4),
    COV_DESC VARCHAR(60),
    ACTIVE_FLAG CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (COV_TYPE)
);

-- CUSTOMER_ADDRESS_T (domain: CUS)
CREATE TABLE CUSTOMER_ADDRESS_T (
    ADDRESS_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CUST_ID VARCHAR(10),
    ADDR_TYPE CHAR(10),
    ADDR_LINE1 VARCHAR(50),
    ADDR_LINE2 VARCHAR(50),
    CITY VARCHAR(50),
    STATE CHAR(2),
    POSTAL_CODE VARCHAR(10),
    EFFECTIVE_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ADDRESS_ID)
);

-- CUSTOMER_CONTACT_T (domain: CUS)
CREATE TABLE CUSTOMER_CONTACT_T (
    CONTACT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CUST_ID VARCHAR(10),
    CONTACT_TYPE CHAR(15),
    CONTACT_NAME VARCHAR(80),
    CONTACT_PHONE VARCHAR(15),
    CONTACT_EMAIL VARCHAR(100),
    PREFERRED_FLAG CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CONTACT_ID)
);

-- CUSTOMER_T (domain: CUS)
CREATE TABLE CUSTOMER_T (
    CUST_ID VARCHAR(10) NOT NULL,
    CUST_TYPE CHAR(1) NOT NULL,
    CUST_NAME VARCHAR(60),
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(50),
    TAX_ID VARCHAR(11),
    DOB DATE,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(15),
    CUST_STATUS CHAR(10),
    ASSIGNED_AGENT VARCHAR(8),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    CUST_GENDER CHAR(1),
    CUST_MARITAL_ST CHAR(1),
    CUST_CREDIT_SCORE INTEGER,
    PRIMARY KEY (CUST_ID)
);

-- DEDUCTIBLE_T (domain: POL)
CREATE TABLE DEDUCTIBLE_T (
    DEDUCT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    COVERAGE_ID VARCHAR(14),
    DED_AMT NUMERIC(11,2),
    DED_TYPE CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DEDUCT_ID)
);

-- DISCOUNT_RULE_T (domain: PRM)
CREATE TABLE DISCOUNT_RULE_T (
    DISC_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DISC_CODE VARCHAR(20),
    DISC_PCT NUMERIC(7,4),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DISC_RULE_ID)
);

-- DOCUMENT_T (domain: DOC)
CREATE TABLE DOCUMENT_T (
    DOCUMENT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    OWNER_TYPE CHAR(10),
    OWNER_KEY VARCHAR(20),
    DOC_TYPE CHAR(10),
    DOC_URI VARCHAR(200),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DOCUMENT_ID)
);

-- ENDORSEMENT_T (domain: POL)
CREATE TABLE ENDORSEMENT_T (
    ENDORSE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    END_TYPE CHAR(4),
    EFF_DATE DATE,
    PREM_CHG NUMERIC(11,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ENDORSE_ID)
);

-- INVOICE_T (domain: BIL)
CREATE TABLE INVOICE_T (
    INVOICE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    BILL_SCHED_ID BIGINT,
    INVOICE_DATE DATE,
    INVOICE_DUE_DATE DATE,
    INVOICE_AMT NUMERIC(11,2),
    INVOICE_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (INVOICE_ID)
);

-- PAYMENT_T (domain: PAY)
CREATE TABLE PAYMENT_T (
    PAYMENT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID BIGINT,
    PAYMENT_DATE DATE,
    PAYMENT_AMT NUMERIC(11,2),
    PAYMENT_TOKEN VARCHAR(40),
    PAYMENT_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PAYMENT_ID)
);

-- POLICY_HISTORY_T (domain: POL)
CREATE TABLE POLICY_HISTORY_T (
    HIST_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    EVENT_CODE CHAR(10),
    EVENT_DATE DATE,
    EVENT_DESC VARCHAR(100),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (HIST_ID)
);

-- POLICY_PROPERTY_T (domain: POL)
CREATE TABLE POLICY_PROPERTY_T (
    PROPERTY_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    PROP_TYPE CHAR(4),
    ADDR_LINE1 VARCHAR(50),
    STATE CHAR(2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PROPERTY_ID)
);

-- POLICY_T (domain: POL)
CREATE TABLE POLICY_T (
    POL_NBR VARCHAR(12),
    CUST_ID VARCHAR(10),
    AGT_ID VARCHAR(8),
    POLICY_TYPE CHAR(4),
    POL_STATUS CHAR(4),
    EFF_DATE DATE,
    EXP_DATE DATE,
    PREM_ANNUAL NUMERIC(13,2),
    RENEWAL_OF_POL VARCHAR(12),
    BILL_FREQ CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (POL_NBR)
);

-- POLICY_VEHICLE_T (domain: POL)
CREATE TABLE POLICY_VEHICLE_T (
    VEHICLE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    VIN VARCHAR(17),
    YEAR INTEGER,
    MAKE VARCHAR(30),
    MODEL VARCHAR(30),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (VEHICLE_ID)
);

-- PREMIUM_CALC_DETAIL_T (domain: PRM)
CREATE TABLE PREMIUM_CALC_DETAIL_T (
    DETAIL_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CALC_ID BIGINT,
    COMPONENT VARCHAR(30),
    COMPONENT_AMT NUMERIC(13,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DETAIL_ID)
);

-- PREMIUM_CALC_T (domain: PRM)
CREATE TABLE PREMIUM_CALC_T (
    CALC_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    FINAL_PREMIUM NUMERIC(13,2),
    CALC_DATE DATE,
    SNAPSHOT_ID VARCHAR(36),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CALC_ID)
);

-- QUOTE_COVERAGE_T (domain: QTE)
CREATE TABLE QUOTE_COVERAGE_T (
    QUOTE_COV_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    QUOTE_ID VARCHAR(12),
    COV_TYPE CHAR(4),
    LIMIT_AMT NUMERIC(13,2),
    DED_AMT NUMERIC(11,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (QUOTE_COV_ID)
);

-- QUOTE_T (domain: QTE)
CREATE TABLE QUOTE_T (
    QUOTE_ID VARCHAR(12),
    CUST_ID VARCHAR(10),
    QUOTE_STATUS CHAR(4),
    QUOTE_PREMIUM NUMERIC(13,2),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (QUOTE_ID)
);

-- RATE_FACTOR_T (domain: PRM)
CREATE TABLE RATE_FACTOR_T (
    RATE_FACTOR_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    RATE_TABLE_ID BIGINT,
    FACTOR_CODE VARCHAR(20),
    FACTOR_VALUE NUMERIC(7,4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RATE_FACTOR_ID)
);

-- RATE_TABLE_T (domain: PRM)
CREATE TABLE RATE_TABLE_T (
    RATE_TABLE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POLICY_TYPE CHAR(4),
    TERRITORY CHAR(4),
    BASE_RATE NUMERIC(7,4),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RATE_TABLE_ID)
);

-- RECOVERY_T (domain: CLM)
CREATE TABLE RECOVERY_T (
    RECOVERY_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    RECOVERY_AMT NUMERIC(13,2),
    RECOVERY_STATUS CHAR(4),
    RECOVERY_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RECOVERY_ID)
);

-- REFUND_T (domain: PAY)
CREATE TABLE REFUND_T (
    REFUND_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    REFUND_DATE DATE,
    REFUND_AMT NUMERIC(11,2),
    REFUND_REASON CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (REFUND_ID)
);

-- REINSURANCE_CESSION_T (domain: REI)
CREATE TABLE REINSURANCE_CESSION_T (
    CESSION_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    TREATY_ID VARCHAR(12),
    CLAIM_ID VARCHAR(12),
    CESSION_AMT NUMERIC(13,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CESSION_ID)
);

-- REINSURANCE_TREATY_T (domain: REI)
CREATE TABLE REINSURANCE_TREATY_T (
    TREATY_ID VARCHAR(12),
    TREATY_NAME VARCHAR(60),
    CESSION_THRESHOLD NUMERIC(13,2),
    TREATY_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (TREATY_ID)
);

-- RISK_SCORE_FACTOR_T (domain: PRM)
CREATE TABLE RISK_SCORE_FACTOR_T (
    RISK_FACTOR_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    FACTOR_CODE VARCHAR(20),
    FACTOR_VALUE NUMERIC(7,4),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RISK_FACTOR_ID)
);

-- ROLE_MENU_T (domain: SEC)
CREATE TABLE ROLE_MENU_T (
    ROLE_CODE VARCHAR(20),
    MENU_OPTION VARCHAR(10),
    ALLOW_FLAG CHAR(1),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ROLE_CODE, MENU_OPTION)
);

-- RPT_PARM_T (domain: RPT)
CREATE TABLE RPT_PARM_T (
    PARM_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    PROGRAM_NAME VARCHAR(10),
    PARM_NAME VARCHAR(30),
    PARM_VALUE VARCHAR(100),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PARM_ID)
);

-- SEC_USER_T (domain: SEC)
CREATE TABLE SEC_USER_T (
    USER_ID VARCHAR(10),
    USER_NAME VARCHAR(60),
    USER_STATUS CHAR(4),
    ROLE_CODE VARCHAR(20),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (USER_ID)
);

-- SURCHARGE_RULE_T (domain: PRM)
CREATE TABLE SURCHARGE_RULE_T (
    SUR_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    SUR_CODE VARCHAR(20),
    SUR_PCT NUMERIC(7,4),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (SUR_RULE_ID)
);

-- TAX_TABLE_T (domain: PRM)
CREATE TABLE TAX_TABLE_T (
    TAX_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    STATE CHAR(2),
    TAX_PCT NUMERIC(7,4),
    EFF_DATE DATE,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (TAX_ID)
);

-- UW_DECISION_T (domain: UND)
CREATE TABLE UW_DECISION_T (
    DECISION_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    REFERRAL_ID BIGINT,
    DECISION_CODE CHAR(4),
    DECISION_USER VARCHAR(10),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DECISION_ID)
);

-- UW_REFERRAL_T (domain: UND)
CREATE TABLE UW_REFERRAL_T (
    REFERRAL_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    POL_NBR VARCHAR(12),
    UW_RULE_ID BIGINT,
    REF_STATUS CHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (REFERRAL_ID)
);

-- UW_RULE_T (domain: UND)
CREATE TABLE UW_RULE_T (
    UW_RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    RULE_CODE VARCHAR(20),
    RULE_DESC VARCHAR(100),
    THRESHOLD_AMT NUMERIC(13,2),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (UW_RULE_ID)
);

-- RPT_RUN_LOG_T (reconciled WO-237 + audit columns)
CREATE TABLE RPT_RUN_LOG_T (
    RUN_LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PGM_NAME VARCHAR(10) NOT NULL,
    RUN_DATE DATE NOT NULL,
    REC_SELECTED INTEGER NOT NULL DEFAULT 0,
    REC_UPDATED INTEGER NOT NULL DEFAULT 0,
    REC_ERRORS INTEGER NOT NULL DEFAULT 0,
    REC_DELINQUENT INTEGER,
    START_TIMESTAMP TIMESTAMP(6) NOT NULL,
    END_TIMESTAMP TIMESTAMP(6) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

-- AUDIT_LOG_T (monthly range partitions on CRT_TIMESTAMP)
CREATE TABLE AUDIT_LOG_T (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    PROGRAM_NAME VARCHAR(10),
    ACTION_CODE VARCHAR(10),
    TABLE_NAME VARCHAR(30),
    RECORD_KEY VARCHAR(40),
    USER_ID VARCHAR(10),
    OLD_VALUE VARCHAR(100),
    NEW_VALUE VARCHAR(100),
    LOG_TIMESTAMP TIMESTAMP,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (LOG_ID, CRT_TIMESTAMP)
) PARTITION BY RANGE (CRT_TIMESTAMP);

CREATE TABLE AUDIT_LOG_T_y2026m01 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE AUDIT_LOG_T_y2026m02 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE AUDIT_LOG_T_y2026m03 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE AUDIT_LOG_T_y2026m04 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE AUDIT_LOG_T_y2026m05 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE AUDIT_LOG_T_y2026m06 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE AUDIT_LOG_T_y2026m07 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE AUDIT_LOG_T_y2026m08 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE AUDIT_LOG_T_y2026m09 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE AUDIT_LOG_T_y2026m10 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE AUDIT_LOG_T_y2026m11 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE AUDIT_LOG_T_y2026m12 PARTITION OF AUDIT_LOG_T FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE AUDIT_LOG_T_default PARTITION OF AUDIT_LOG_T DEFAULT;

-- COMMISSION_LEDGER_T (code-witnessed, not in 55-table inventory)
CREATE TABLE COMMISSION_LEDGER_T (
    LEDGER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AGT_ID VARCHAR(8) NOT NULL,
    BILL_SCHED_ID BIGINT NOT NULL,
    COMM_RATE NUMERIC(7,4),
    COMMISSION_AMT NUMERIC(11,2) NOT NULL,
    CALC_DATE DATE NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    CONSTRAINT uq_comm_ledger_bill_sched UNIQUE (BILL_SCHED_ID)
);

-- outbox_events (transactional outbox for domain event relay)
CREATE TABLE outbox_events (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AGGREGATE_TYPE VARCHAR(100) NOT NULL,
    AGGREGATE_ID VARCHAR(100) NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    PAYLOAD JSONB NOT NULL,
    IDEMPOTENCY_KEY UUID NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT TIMESTAMP,
    LAST_ERROR VARCHAR(500),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    CONSTRAINT uq_outbox_idempotency UNIQUE (IDEMPOTENCY_KEY)
);
CREATE INDEX idx_outbox_relay ON outbox_events (STATUS, NEXT_ATTEMPT_AT) WHERE STATUS = 'PENDING';

-- Foreign key constraints

ALTER TABLE CUSTOMER_T ADD CONSTRAINT fk_customer_t_assigned_agent FOREIGN KEY (ASSIGNED_AGENT) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE CUSTOMER_ADDRESS_T ADD CONSTRAINT fk_customer_address_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE CUSTOMER_CONTACT_T ADD CONSTRAINT fk_customer_contact_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE AGENT_LICENSE_T ADD CONSTRAINT fk_agent_license_t_agt_id FOREIGN KEY (AGT_ID) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE AGENT_COMMISSION_T ADD CONSTRAINT fk_agent_commission_t_agt_id FOREIGN KEY (AGT_ID) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE AGENT_COMMISSION_T ADD CONSTRAINT fk_agent_commission_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE COMMISSION_T ADD CONSTRAINT fk_commission_t_agt_id FOREIGN KEY (AGT_ID) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE COMMISSION_T ADD CONSTRAINT fk_commission_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE QUOTE_T ADD CONSTRAINT fk_quote_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE QUOTE_COVERAGE_T ADD CONSTRAINT fk_quote_coverage_t_quote_id FOREIGN KEY (QUOTE_ID) REFERENCES QUOTE_T (QUOTE_ID);
ALTER TABLE UW_REFERRAL_T ADD CONSTRAINT fk_uw_referral_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE UW_REFERRAL_T ADD CONSTRAINT fk_uw_referral_t_uw_rule_id FOREIGN KEY (UW_RULE_ID) REFERENCES UW_RULE_T (UW_RULE_ID);
ALTER TABLE UW_DECISION_T ADD CONSTRAINT fk_uw_decision_t_referral_id FOREIGN KEY (REFERRAL_ID) REFERENCES UW_REFERRAL_T (REFERRAL_ID);
ALTER TABLE POLICY_T ADD CONSTRAINT fk_policy_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE POLICY_T ADD CONSTRAINT fk_policy_t_agt_id FOREIGN KEY (AGT_ID) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE COVERAGE_T ADD CONSTRAINT fk_coverage_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE DEDUCTIBLE_T ADD CONSTRAINT fk_deductible_t_coverage_id FOREIGN KEY (COVERAGE_ID) REFERENCES COVERAGE_T (COVERAGE_ID);
ALTER TABLE POLICY_HISTORY_T ADD CONSTRAINT fk_policy_history_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE POLICY_VEHICLE_T ADD CONSTRAINT fk_policy_vehicle_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE POLICY_PROPERTY_T ADD CONSTRAINT fk_policy_property_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE ENDORSEMENT_T ADD CONSTRAINT fk_endorsement_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE RATE_FACTOR_T ADD CONSTRAINT fk_rate_factor_t_rate_table_id FOREIGN KEY (RATE_TABLE_ID) REFERENCES RATE_TABLE_T (RATE_TABLE_ID);
ALTER TABLE PREMIUM_CALC_T ADD CONSTRAINT fk_premium_calc_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE PREMIUM_CALC_DETAIL_T ADD CONSTRAINT fk_premium_calc_detail_t_calc_id FOREIGN KEY (CALC_ID) REFERENCES PREMIUM_CALC_T (CALC_ID);
ALTER TABLE BILLING_PLAN_T ADD CONSTRAINT fk_billing_plan_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE BILLING_SCHEDULE_T ADD CONSTRAINT fk_billing_schedule_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE BILLING_SCHEDULE_T ADD CONSTRAINT fk_billing_schedule_t_bill_plan_id FOREIGN KEY (BILL_PLAN_ID) REFERENCES BILLING_PLAN_T (BILL_PLAN_ID);
ALTER TABLE BILLING_NOTICE_T ADD CONSTRAINT fk_billing_notice_t_bill_sched_id FOREIGN KEY (BILL_SCHED_ID) REFERENCES BILLING_SCHEDULE_T (BILL_SCHED_ID);
ALTER TABLE BILLING_NOTICE_T ADD CONSTRAINT fk_billing_notice_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE INVOICE_T ADD CONSTRAINT fk_invoice_t_bill_sched_id FOREIGN KEY (BILL_SCHED_ID) REFERENCES BILLING_SCHEDULE_T (BILL_SCHED_ID);
ALTER TABLE PAYMENT_T ADD CONSTRAINT fk_payment_t_invoice_id FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE_T (INVOICE_ID);
ALTER TABLE REFUND_T ADD CONSTRAINT fk_refund_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE CLAIM_T ADD CONSTRAINT fk_claim_t_pol_nbr FOREIGN KEY (POL_NBR) REFERENCES POLICY_T (POL_NBR);
ALTER TABLE CLAIM_T ADD CONSTRAINT fk_claim_t_cust_id FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_T (CUST_ID);
ALTER TABLE CLAIM_RESERVE_T ADD CONSTRAINT fk_claim_reserve_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE CLAIM_RESERVE_HISTORY_T ADD CONSTRAINT fk_claim_reserve_history_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE CLAIM_PAYMENT_T ADD CONSTRAINT fk_claim_payment_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE CLAIM_PAYMENT_T ADD CONSTRAINT fk_claim_payment_t_adjuster_id FOREIGN KEY (ADJUSTER_ID) REFERENCES CLAIM_ADJUSTER_T (ADJUSTER_ID);
ALTER TABLE CLAIM_NOTE_T ADD CONSTRAINT fk_claim_note_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE CLAIM_DOCUMENT_T ADD CONSTRAINT fk_claim_document_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE APPROVAL_T ADD CONSTRAINT fk_approval_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE APPROVAL_T ADD CONSTRAINT fk_approval_t_reserve_hist_id FOREIGN KEY (RESERVE_HIST_ID) REFERENCES CLAIM_RESERVE_T (RESERVE_HIST_ID);
ALTER TABLE APPROVAL_T ADD CONSTRAINT fk_approval_t_approver_id FOREIGN KEY (APPROVER_ID) REFERENCES CLAIM_ADJUSTER_T (ADJUSTER_ID);
ALTER TABLE RECOVERY_T ADD CONSTRAINT fk_recovery_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE REINSURANCE_CESSION_T ADD CONSTRAINT fk_reinsurance_cession_t_treaty_id FOREIGN KEY (TREATY_ID) REFERENCES REINSURANCE_TREATY_T (TREATY_ID);
ALTER TABLE REINSURANCE_CESSION_T ADD CONSTRAINT fk_reinsurance_cession_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID);
ALTER TABLE COMMISSION_LEDGER_T ADD CONSTRAINT fk_commission_ledger_t_agt_id FOREIGN KEY (AGT_ID) REFERENCES AGENT_T (AGT_ID);
ALTER TABLE COMMISSION_LEDGER_T ADD CONSTRAINT fk_commission_ledger_t_bill_sched_id FOREIGN KEY (BILL_SCHED_ID) REFERENCES BILLING_SCHEDULE_T (BILL_SCHED_ID);

-- Check constraints

ALTER TABLE BILLING_SCHEDULE_T ADD CONSTRAINT chk_bill_sched_status CHECK (SCHED_STATUS IN ('O','P','V','D','L'));
ALTER TABLE CLAIM_PAYMENT_T ADD CONSTRAINT chk_claim_pmt_status CHECK (PAYMENT_STATUS IN ('I','P','V'));
ALTER TABLE APPROVAL_T ADD CONSTRAINT chk_approval_status CHECK (APPROVAL_STATUS IN ('REQUESTED','APPROVED','DENIED','PENDING'));

