-- PCIS V2 Reference Data Seed (WO-151)
-- Authority: BIL003B billing frequency intervals, PCIS_Database_Design.md reference domains
-- All monetary literals use explicit NUMERIC precision and scale.

-- Billing frequency codes (BIL003B: M/Q/S/A)
INSERT INTO CODE_TABLE_T (CODE_TYPE, CODE_VALUE, CODE_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('BILL_FREQ', 'M', 'Monthly billing', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ', 'Q', 'Quarterly billing', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ', 'S', 'Semi-annual billing', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ', 'A', 'Annual billing', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Billing frequency interval mapping in months (BIL003B: M=1, Q=3, S=6, A=12)
INSERT INTO CODE_TABLE_T (CODE_TYPE, CODE_VALUE, CODE_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('BILL_FREQ_INTERVAL', 'M', '1', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ_INTERVAL', 'Q', '3', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ_INTERVAL', 'S', '6', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_FREQ_INTERVAL', 'A', '12', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Billing schedule status domain (includes void per design reconciliation)
INSERT INTO CODE_TABLE_T (CODE_TYPE, CODE_VALUE, CODE_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('BILL_SCHED_STATUS', 'O', 'Open', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_SCHED_STATUS', 'P', 'Paid', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_SCHED_STATUS', 'V', 'Void', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_SCHED_STATUS', 'D', 'Delinquent', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('BILL_SCHED_STATUS', 'L', 'Late', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Reserve status domain
INSERT INTO CODE_TABLE_T (CODE_TYPE, CODE_VALUE, CODE_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('RESERVE_STATUS', 'AP', 'Approved', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('RESERVE_STATUS', 'PD', 'Paid', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('RESERVE_STATUS', 'CL', 'Closed', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Claim type codes
INSERT INTO CODE_TABLE_T (CODE_TYPE, CODE_VALUE, CODE_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('CLAIM_TYPE', 'AUTO', 'Automobile claim', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('CLAIM_TYPE', 'PROP', 'Property claim', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('CLAIM_TYPE', 'LIAB', 'Liability claim', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Coverage types
INSERT INTO COVERAGE_TYPE_T (COV_TYPE, COV_DESC, ACTIVE_FLAG, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('LIAB', 'Bodily injury liability', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('PROP', 'Property damage', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('COLL', 'Collision', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('COMP', 'Comprehensive', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Cancellation reasons
INSERT INTO CANCELLATION_REASON_T (CANCEL_REASON, REASON_DESC, REFUND_ELIGIBLE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('NPAY', 'Non-payment of premium', 'N', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('INSR', 'Insured request', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('FRAU', 'Fraud determination', 'N', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('REWR', 'Rewrite to new policy', 'Y', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Commission rates (explicit NUMERIC scale)
INSERT INTO COMMISSION_RATE_T (POLICY_TYPE, COMM_RATE, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('AUTO', CAST(0.1200 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('HOME', CAST(0.1500 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('COMM', CAST(0.1000 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

-- Rating reference tables
INSERT INTO RATE_TABLE_T (POLICY_TYPE, TERRITORY, BASE_RATE, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('AUTO', 'NE01', CAST(1.2500 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('HOME', 'NE01', CAST(0.8750 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

INSERT INTO RATE_FACTOR_T (RATE_TABLE_ID, FACTOR_CODE, FACTOR_VALUE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
SELECT RATE_TABLE_ID, 'TERR', CAST(1.0500 AS NUMERIC(7,4)), 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP
FROM RATE_TABLE_T WHERE POLICY_TYPE = 'AUTO' AND TERRITORY = 'NE01';

INSERT INTO RATE_FACTOR_T (RATE_TABLE_ID, FACTOR_CODE, FACTOR_VALUE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
SELECT RATE_TABLE_ID, 'TERR', CAST(0.9800 AS NUMERIC(7,4)), 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP
FROM RATE_TABLE_T WHERE POLICY_TYPE = 'HOME' AND TERRITORY = 'NE01';

INSERT INTO DISCOUNT_RULE_T (DISC_CODE, DISC_PCT, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('MULTI', CAST(0.0500 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('SAFE', CAST(0.0300 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

INSERT INTO SURCHARGE_RULE_T (SUR_CODE, SUR_PCT, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('YOUNG', CAST(0.1500 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

INSERT INTO TAX_TABLE_T (STATE, TAX_PCT, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('NY', CAST(0.0200 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('CA', CAST(0.0250 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

INSERT INTO RISK_SCORE_FACTOR_T (FACTOR_CODE, FACTOR_VALUE, EFF_DATE, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('CREDIT', CAST(0.9000 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('CLAIMS', CAST(1.1000 AS NUMERIC(7,4)), DATE '2024-01-01', 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);

INSERT INTO UW_RULE_T (RULE_CODE, RULE_DESC, THRESHOLD_AMT, CRT_USER, CRT_TIMESTAMP, UPD_USER, UPD_TIMESTAMP)
VALUES
    ('HIGHVAL', 'High property value referral', CAST(500000.00 AS NUMERIC(13,2)), 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP),
    ('YOUNGDR', 'Young driver referral', CAST(25000.00 AS NUMERIC(13,2)), 'SEED', CURRENT_TIMESTAMP, 'SEED', CURRENT_TIMESTAMP);
