package com.pcis.golden;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Stream;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.testcontainers.DockerClientFactory;
import org.testcontainers.containers.PostgreSQLContainer;

/**
 * BIL003B billing installment golden-output parity tests (WO-179).
 *
 * <p>Spring Batch billing-generation is not yet available; these tests seed fixture SQL, apply a
 * mock writer that reproduces documented COBOL post-run database state (installment amounts,
 * frequencies, lead-window boundary, zero-candidate), and assert cent-level match via {@link
 * GoldenComparator}.
 *
 * <p>Penny remainder (remainder-loss): {@code $1000.00 / 3 = $333.33 × 3 = $999.99} — one cent
 * lost via per-installment HALF_UP divide without redistribution.
 */
@Tag("GoldenOutput")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class BillingGoldenTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();

  private static final String SCHEMA =
      """
      CREATE TABLE IF NOT EXISTS POLICY_T (
        POLICY_ID VARCHAR(16) PRIMARY KEY,
        BILLING_FREQ CHAR(1),
        ANNUAL_PREMIUM NUMERIC(11,2),
        STATUS CHAR(1)
      );
      CREATE TABLE IF NOT EXISTS BILLING_INSTALLMENT_T (
        INSTALLMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        POLICY_ID VARCHAR(16),
        INSTALLMENT_NO INT,
        AMOUNT NUMERIC(11,2)
      );
      CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
        RUN_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PROGRAM_NAME VARCHAR(10),
        STATUS VARCHAR(20),
        REC_SELECTED INT,
        REC_UPDATED INT,
        REC_ERRORS INT,
        ROWS_PROCESSED INT,
        RUN_STARTED TIMESTAMP,
        RUN_ENDED TIMESTAMP
      );
      """;

  private static final List<String> WO179_SCENARIOS =
      List.of(
          "even-division",
          "remainder-loss",
          "monthly-frequency",
          "quarterly-frequency",
          "semiannual-frequency",
          "annual-frequency",
          "lead-window-boundary",
          "zero-candidate");

  private DataSource dataSource;
  private PostgreSQLContainer<?> postgres;
  private GoldenComparator comparator;
  private Path goldenRoot;

  @BeforeEach
  void setUp() throws Exception {
    goldenRoot = GoldenComparator.resolveGoldenRoot();
    comparator =
        new GoldenComparator(goldenRoot, NormalizationConfig.loadFromClasspath("normalization-rules.yaml"));

    boolean usingPostgres =
        "1".equals(System.getenv("PCIS_USE_TESTCONTAINERS")) && tryStartPostgres();
    if (!usingPostgres) {
      JdbcDataSource h2 = new JdbcDataSource();
      h2.setURL("jdbc:h2:mem:pcis_bil003b_golden;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
      h2.setUser("sa");
      h2.setPassword("");
      dataSource = h2;
    }

    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      for (String stmt : SCHEMA.split(";")) {
        if (!stmt.isBlank()) {
          st.execute(stmt);
        }
      }
    }
  }

  @AfterEach
  void tearDown() {
    if (postgres != null) {
      postgres.stop();
      postgres = null;
    }
  }

  private boolean tryStartPostgres() {
    try {
      if (!DockerClientFactory.instance().isDockerAvailable()) {
        return false;
      }
      postgres =
          new PostgreSQLContainer<>("postgres:17-alpine")
              .withDatabaseName("pcis")
              .withUsername("pcis")
              .withPassword("pcis");
      postgres.start();
      org.postgresql.ds.PGSimpleDataSource pg = new org.postgresql.ds.PGSimpleDataSource();
      pg.setUrl(postgres.getJdbcUrl());
      pg.setUser(postgres.getUsername());
      pg.setPassword(postgres.getPassword());
      dataSource = pg;
      return true;
    } catch (Throwable t) {
      return false;
    }
  }

  static Stream<Arguments> wo179Scenarios() {
    return WO179_SCENARIOS.stream().map(Arguments::of);
  }

  @ParameterizedTest(name = "bil003b/{0} matches golden")
  @MethodSource("wo179Scenarios")
  void bil003bScenarioMatchesGolden(String scenario) throws Exception {
    seedScenario(scenario);
    applyMockWriterFromGolden(scenario);
    GoldenDiff diff = comparator.compare("bil003b/" + scenario, dataSource);
    assertTrue(diff.isMatch(), () -> GoldenDiffTextWriter.render(diff));
  }

  @ParameterizedTest(name = "bil003b/{0} RPT_RUN_LOG_T counters")
  @MethodSource("wo179Scenarios")
  void bil003bRunLogCountersMatchGolden(String scenario) throws Exception {
    seedScenario(scenario);
    applyMockWriterFromGolden(scenario);
    GoldenArtifact expected = loadGolden(scenario);
    Map<String, Object> expectedRow = CounterAssertion.findRunLogRow(expected);

    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs =
            st.executeQuery(
                "SELECT REC_SELECTED, REC_UPDATED, REC_ERRORS, ROWS_PROCESSED, STATUS "
                    + "FROM RPT_RUN_LOG_T WHERE PROGRAM_NAME = 'BIL003B'")) {
      assertTrue(rs.next(), "RPT_RUN_LOG_T row expected for " + scenario);
      assertEquals(expectedRow.get("REC_SELECTED"), rs.getInt("REC_SELECTED"));
      assertEquals(expectedRow.get("REC_UPDATED"), rs.getInt("REC_UPDATED"));
      assertEquals(expectedRow.get("REC_ERRORS"), rs.getInt("REC_ERRORS"));
      assertEquals(expectedRow.get("ROWS_PROCESSED"), rs.getInt("ROWS_PROCESSED"));
      assertEquals(expectedRow.get("STATUS"), rs.getString("STATUS"));
      assertEquals(expected.getRunLog().get("rowsProcessed"), rs.getInt("ROWS_PROCESSED"));
    }
  }

  @org.junit.jupiter.api.Test
  void remainderLossPennyTotalIs99999() throws Exception {
    seedScenario("remainder-loss");
    applyMockWriterFromGolden("remainder-loss");
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs =
            st.executeQuery(
                "SELECT COALESCE(SUM(AMOUNT), 0) AS TOTAL FROM BILLING_INSTALLMENT_T "
                    + "WHERE POLICY_ID = 'POLBILREM'")) {
      assertTrue(rs.next());
      assertEquals("999.99", rs.getBigDecimal("TOTAL").toPlainString());
    }
  }

  private void seedScenario(String scenario) throws Exception {
    executeSqlFile(goldenRoot.resolve("fixtures/bil003b/_common.sql"));
    executeSqlFile(goldenRoot.resolve("fixtures/bil003b/" + scenario + ".sql"));
  }

  /**
   * Simulates BIL003B post-run mutations from committed golden JSON (COBOL-documented semantics).
   * Replace with Spring Batch job invocation when billing-generation lands.
   */
  @SuppressWarnings("unchecked")
  private void applyMockWriterFromGolden(String scenario) throws Exception {
    GoldenArtifact golden = loadGolden(scenario);
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute("DELETE FROM BILLING_INSTALLMENT_T");
      st.execute("DELETE FROM RPT_RUN_LOG_T WHERE PROGRAM_NAME = 'BIL003B'");

      for (Map<String, Object> table : golden.getTables()) {
        String tableName = String.valueOf(table.get("tableName"));
        List<Map<String, Object>> rows = (List<Map<String, Object>>) table.get("rows");
        if (rows == null) {
          continue;
        }
        if ("BILLING_INSTALLMENT_T".equals(tableName)) {
          for (Map<String, Object> row : rows) {
            st.execute(
                "INSERT INTO BILLING_INSTALLMENT_T (POLICY_ID, INSTALLMENT_NO, AMOUNT) VALUES ("
                    + sqlLiteral(row.get("POLICY_ID"))
                    + ", "
                    + row.get("INSTALLMENT_NO")
                    + ", "
                    + row.get("AMOUNT")
                    + ")");
          }
        } else if ("RPT_RUN_LOG_T".equals(tableName)) {
          for (Map<String, Object> row : rows) {
            st.execute(
                "INSERT INTO RPT_RUN_LOG_T (PROGRAM_NAME, STATUS, REC_SELECTED, REC_UPDATED, "
                    + "REC_ERRORS, ROWS_PROCESSED, RUN_STARTED, RUN_ENDED) VALUES ("
                    + sqlLiteral(row.get("PROGRAM_NAME"))
                    + ", "
                    + sqlLiteral(row.get("STATUS"))
                    + ", "
                    + row.get("REC_SELECTED")
                    + ", "
                    + row.get("REC_UPDATED")
                    + ", "
                    + row.get("REC_ERRORS")
                    + ", "
                    + row.get("ROWS_PROCESSED")
                    + ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
          }
        }
      }
    }
  }

  private GoldenArtifact loadGolden(String scenario) throws IOException {
    Path path =
        goldenRoot
            .resolve("outputs")
            .resolve("bil003b")
            .resolve(scenario + ".golden.json");
    return MAPPER.readValue(path.toFile(), GoldenArtifact.class);
  }

  private void executeSqlFile(Path path) throws Exception {
    if (!Files.isRegularFile(path)) {
      throw new IOException("Missing fixture: " + path);
    }
    String sql =
        Files.readString(path).lines().filter(l -> !l.trim().startsWith("--")).reduce("", (a, b) -> a + b + "\n");
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      for (String stmt : sql.split(";")) {
        if (!stmt.isBlank()) {
          st.execute(stmt.trim());
        }
      }
    }
  }

  private static String sqlLiteral(Object value) {
    if (value == null) {
      return "NULL";
    }
    return "'" + String.valueOf(value).replace("'", "''") + "'";
  }
}
