package com.pcis.golden;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.testcontainers.DockerClientFactory;
import org.testcontainers.containers.PostgreSQLContainer;

/**
 * CLM006B claims payment reserve drawdown golden-output parity tests (WO-180).
 *
 * <p>Spring Batch claim-payment is not yet available; these tests seed fixture SQL, apply a mock
 * writer that reproduces documented COBOL post-run database state (reserve status transitions,
 * payment amounts, reinsurance RECOVERY_T referrals, run-log counters), and assert cent-level
 * match via {@link GoldenComparator}.
 *
 * <p>Legacy baseline has no SECCHK01 authority gate — payments proceed when {@code RESERVE_AMT}
 * exceeds {@code AUTHORITY_LIMIT}. Reinsurance cession uses a strictly-greater-than {@code
 * 100000.00} check: {@code $100000.00} does not create RECOVERY_T; {@code $100000.01} does.
 */
@Tag("GoldenOutput")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ClaimsPaymentGoldenTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();

  private static final String SCHEMA =
      """
      CREATE TABLE IF NOT EXISTS CLAIM_RESERVE_T (
        CLAIM_ID VARCHAR(16),
        RESERVE_ID VARCHAR(16),
        RESERVE_STATUS CHAR(2),
        RESERVE_AMT NUMERIC(11,2),
        AUTHORITY_LIMIT NUMERIC(11,2)
      );
      CREATE TABLE IF NOT EXISTS CLAIM_PAYMENT_T (
        PAYMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        CLAIM_ID VARCHAR(16),
        PAYMENT_AMT NUMERIC(11,2),
        CREATED_AT TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS RECOVERY_T (
        RECOVERY_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        CLAIM_ID VARCHAR(16),
        RECOVERY_AMT NUMERIC(11,2),
        RECOVERY_STATUS CHAR(4),
        RECOVERY_DATE DATE
      );
      CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
        RUN_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PROGRAM_NAME VARCHAR(10),
        STATUS VARCHAR(20),
        REC_SELECTED INT,
        REC_UPDATED INT,
        REC_ERRORS INT,
        ROWS_PROCESSED INT,
        RUN_STARTED TIMESTAMP,
        RUN_ENDED TIMESTAMP
      );
      """;

  private static final List<String> WO180_SCENARIOS =
      List.of(
          "single-reserve-payment",
          "multiple-reserves",
          "zero-payable",
          "authority-limit-exceeded",
          "cession-below-threshold",
          "cession-at-threshold",
          "cession-above-threshold");

  private DataSource dataSource;
  private PostgreSQLContainer<?> postgres;
  private GoldenComparator comparator;
  private Path goldenRoot;

  @BeforeEach
  void setUp() throws Exception {
    goldenRoot = GoldenComparator.resolveGoldenRoot();
    comparator =
        new GoldenComparator(goldenRoot, NormalizationConfig.loadFromClasspath("normalization-rules.yaml"));

    boolean usingPostgres =
        "1".equals(System.getenv("PCIS_USE_TESTCONTAINERS")) && tryStartPostgres();
    if (!usingPostgres) {
      JdbcDataSource h2 = new JdbcDataSource();
      h2.setURL("jdbc:h2:mem:pcis_clm006b_golden;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
      h2.setUser("sa");
      h2.setPassword("");
      dataSource = h2;
    }

    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      for (String stmt : SCHEMA.split(";")) {
        if (!stmt.isBlank()) {
          st.execute(stmt);
        }
      }
    }
  }

  @AfterEach
  void tearDown() {
    if (postgres != null) {
      postgres.stop();
      postgres = null;
    }
  }

  private boolean tryStartPostgres() {
    try {
      if (!DockerClientFactory.instance().isDockerAvailable()) {
        return false;
      }
      postgres =
          new PostgreSQLContainer<>("postgres:17-alpine")
              .withDatabaseName("pcis")
              .withUsername("pcis")
              .withPassword("pcis");
      postgres.start();
      org.postgresql.ds.PGSimpleDataSource pg = new org.postgresql.ds.PGSimpleDataSource();
      pg.setUrl(postgres.getJdbcUrl());
      pg.setUser(postgres.getUsername());
      pg.setPassword(postgres.getPassword());
      dataSource = pg;
      return true;
    } catch (Throwable t) {
      return false;
    }
  }

  static Stream<Arguments> wo180Scenarios() {
    return WO180_SCENARIOS.stream().map(Arguments::of);
  }

  @ParameterizedTest(name = "clm006b/{0} matches golden")
  @MethodSource("wo180Scenarios")
  void clm006bScenarioMatchesGolden(String scenario) throws Exception {
    seedScenario(scenario);
    applyMockWriterFromGolden(scenario);
    GoldenDiff diff = comparator.compare("clm006b/" + scenario, dataSource);
    assertTrue(diff.isMatch(), () -> GoldenDiffTextWriter.render(diff));
  }

  @ParameterizedTest(name = "clm006b/{0} RPT_RUN_LOG_T counters")
  @MethodSource("wo180Scenarios")
  void clm006bRunLogCountersMatchGolden(String scenario) throws Exception {
    seedScenario(scenario);
    applyMockWriterFromGolden(scenario);
    GoldenArtifact expected = loadGolden(scenario);
    Map<String, Object> expectedRow = CounterAssertion.findRunLogRow(expected);

    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs =
            st.executeQuery(
                "SELECT REC_SELECTED, REC_UPDATED, REC_ERRORS, ROWS_PROCESSED, STATUS "
                    + "FROM RPT_RUN_LOG_T WHERE PROGRAM_NAME = 'CLM006B'")) {
      assertTrue(rs.next(), "RPT_RUN_LOG_T row expected for " + scenario);
      assertEquals(expectedRow.get("REC_SELECTED"), rs.getInt("REC_SELECTED"));
      assertEquals(expectedRow.get("REC_UPDATED"), rs.getInt("REC_UPDATED"));
      assertEquals(expectedRow.get("REC_ERRORS"), rs.getInt("REC_ERRORS"));
      assertEquals(expectedRow.get("ROWS_PROCESSED"), rs.getInt("ROWS_PROCESSED"));
      assertEquals(expectedRow.get("STATUS"), rs.getString("STATUS"));
      assertEquals(expected.getRunLog().get("rowsProcessed"), rs.getInt("ROWS_PROCESSED"));
    }
  }

  @Test
  void cessionAtThresholdDoesNotCreateRecovery() throws Exception {
    seedScenario("cession-at-threshold");
    applyMockWriterFromGolden("cession-at-threshold");
    assertRecoveryCount(0);
  }

  @Test
  void cessionAboveThresholdCreatesRecovery() throws Exception {
    seedScenario("cession-above-threshold");
    applyMockWriterFromGolden("cession-above-threshold");
    assertRecoveryCount(1);
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs = st.executeQuery("SELECT RECOVERY_AMT FROM RECOVERY_T WHERE CLAIM_ID = 'CLM0007001'")) {
      assertTrue(rs.next());
      assertEquals("100000.01", rs.getBigDecimal("RECOVERY_AMT").toPlainString());
    }
  }

  @Test
  void authorityLimitExceededStillPaysWithoutSecchk01() throws Exception {
    seedScenario("authority-limit-exceeded");
    applyMockWriterFromGolden("authority-limit-exceeded");
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs =
            st.executeQuery(
                "SELECT COUNT(*) AS CNT FROM CLAIM_PAYMENT_T WHERE CLAIM_ID = 'CLM0004001'")) {
      assertTrue(rs.next());
      assertEquals(1, rs.getInt("CNT"));
    }
  }

  private void assertRecoveryCount(int expected) throws Exception {
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement();
        var rs = st.executeQuery("SELECT COUNT(*) AS CNT FROM RECOVERY_T")) {
      assertTrue(rs.next());
      assertEquals(expected, rs.getInt("CNT"));
    }
  }

  private void seedScenario(String scenario) throws Exception {
    executeSqlFile(goldenRoot.resolve("fixtures/clm006b/_common.sql"));
    executeSqlFile(goldenRoot.resolve("fixtures/clm006b/" + scenario + ".sql"));
  }

  /**
   * Simulates CLM006B post-run mutations from committed golden JSON (COBOL-documented semantics).
   * Replace with Spring Batch job invocation when claim-payment lands.
   */
  @SuppressWarnings("unchecked")
  private void applyMockWriterFromGolden(String scenario) throws Exception {
    GoldenArtifact golden = loadGolden(scenario);
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute("DELETE FROM RECOVERY_T");
      st.execute("DELETE FROM CLAIM_PAYMENT_T");
      st.execute("DELETE FROM CLAIM_RESERVE_T");
      st.execute("DELETE FROM RPT_RUN_LOG_T WHERE PROGRAM_NAME = 'CLM006B'");

      for (Map<String, Object> table : golden.getTables()) {
        String tableName = String.valueOf(table.get("tableName"));
        List<Map<String, Object>> rows = (List<Map<String, Object>>) table.get("rows");
        if (rows == null) {
          continue;
        }
        switch (tableName) {
          case "CLAIM_RESERVE_T" -> {
            for (Map<String, Object> row : rows) {
              st.execute(
                  "INSERT INTO CLAIM_RESERVE_T (CLAIM_ID, RESERVE_ID, RESERVE_STATUS, "
                      + "RESERVE_AMT, AUTHORITY_LIMIT) VALUES ("
                      + sqlLiteral(row.get("CLAIM_ID"))
                      + ", "
                      + sqlLiteral(row.get("RESERVE_ID"))
                      + ", "
                      + sqlLiteral(row.get("RESERVE_STATUS"))
                      + ", "
                      + row.get("RESERVE_AMT")
                      + ", "
                      + row.get("AUTHORITY_LIMIT")
                      + ")");
            }
          }
          case "CLAIM_PAYMENT_T" -> {
            List<Map<String, Object>> sorted = new ArrayList<>(rows);
            sorted.sort(
                (a, b) -> {
                  int byClaim =
                      String.valueOf(a.get("CLAIM_ID")).compareTo(String.valueOf(b.get("CLAIM_ID")));
                  if (byClaim != 0) {
                    return byClaim;
                  }
                  return String.valueOf(a.get("PAYMENT_AMT"))
                      .compareTo(String.valueOf(b.get("PAYMENT_AMT")));
                });
            for (Map<String, Object> row : sorted) {
              st.execute(
                  "INSERT INTO CLAIM_PAYMENT_T (CLAIM_ID, PAYMENT_AMT, CREATED_AT) VALUES ("
                      + sqlLiteral(row.get("CLAIM_ID"))
                      + ", "
                      + row.get("PAYMENT_AMT")
                      + ", CURRENT_TIMESTAMP)");
            }
          }
          case "RECOVERY_T" -> {
            for (Map<String, Object> row : rows) {
              st.execute(
                  "INSERT INTO RECOVERY_T (CLAIM_ID, RECOVERY_AMT, RECOVERY_STATUS, RECOVERY_DATE) "
                      + "VALUES ("
                      + sqlLiteral(row.get("CLAIM_ID"))
                      + ", "
                      + row.get("RECOVERY_AMT")
                      + ", "
                      + sqlLiteral(row.get("RECOVERY_STATUS"))
                      + ", "
                      + sqlLiteral(row.get("RECOVERY_DATE"))
                      + ")");
            }
          }
          case "RPT_RUN_LOG_T" -> {
            for (Map<String, Object> row : rows) {
              st.execute(
                  "INSERT INTO RPT_RUN_LOG_T (PROGRAM_NAME, STATUS, REC_SELECTED, REC_UPDATED, "
                      + "REC_ERRORS, ROWS_PROCESSED, RUN_STARTED, RUN_ENDED) VALUES ("
                      + sqlLiteral(row.get("PROGRAM_NAME"))
                      + ", "
                      + sqlLiteral(row.get("STATUS"))
                      + ", "
                      + row.get("REC_SELECTED")
                      + ", "
                      + row.get("REC_UPDATED")
                      + ", "
                      + row.get("REC_ERRORS")
                      + ", "
                      + row.get("ROWS_PROCESSED")
                      + ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
            }
          }
          default -> {}
        }
      }
    }
  }

  private GoldenArtifact loadGolden(String scenario) throws IOException {
    Path path =
        goldenRoot.resolve("outputs").resolve("clm006b").resolve(scenario + ".golden.json");
    return MAPPER.readValue(path.toFile(), GoldenArtifact.class);
  }

  private void executeSqlFile(Path path) throws Exception {
    if (!Files.isRegularFile(path)) {
      throw new IOException("Missing fixture: " + path);
    }
    String sql =
        Files.readString(path).lines().filter(l -> !l.trim().startsWith("--")).reduce("", (a, b) -> a + b + "\n");
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      for (String stmt : sql.split(";")) {
        if (!stmt.isBlank()) {
          st.execute(stmt.trim());
        }
      }
    }
  }

  private static String sqlLiteral(Object value) {
    if (value == null) {
      return "NULL";
    }
    return "'" + String.valueOf(value).replace("'", "''") + "'";
  }
}
