package com.pcis.golden;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** Extra coverage for capture paths, rules loading, and default table catalogs. */
class GoldenOutputCaptureCoverageTest {

  @TempDir Path temp;

  private JdbcDataSource dataSource;
  private GoldenCaptureContext context;
  private NormalizationRules rules;

  @BeforeEach
  void setUp() throws Exception {
    rules = NormalizationRules.loadFromClasspath("normalization-rules.yaml");
    context = GoldenCaptureContext.fromRulesDefault(rules);
    dataSource = new JdbcDataSource();
    dataSource.setURL("jdbc:h2:mem:pcis_cov;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    dataSource.setUser("sa");
    dataSource.setPassword("");
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute(
          """
          CREATE TABLE IF NOT EXISTS CLAIM_RESERVE_T (
            CLAIM_ID VARCHAR(16), RESERVE_ID VARCHAR(16), RESERVE_STATUS CHAR(2),
            RESERVE_AMT NUMERIC(11,2), AUTHORITY_LIMIT NUMERIC(11,2)
          );
          CREATE TABLE IF NOT EXISTS CLAIM_PAYMENT_T (
            PAYMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
            CLAIM_ID VARCHAR(16), PAYMENT_AMT NUMERIC(11,2), CREATED_AT TIMESTAMP
          );
          CREATE TABLE IF NOT EXISTS COMMISSION_T (
            POLICY_ID VARCHAR(16), AGENT_ID VARCHAR(10), PREMIUM_AMT NUMERIC(11,2),
            COMM_CALC_FLAG CHAR(1), COMMISSION_AMT NUMERIC(9,2)
          );
          CREATE TABLE IF NOT EXISTS AUDIT_LOG_T (
            LOG_ID BIGINT, PROGRAM_NAME VARCHAR(10), ACTION_CODE VARCHAR(3),
            TABLE_NAME VARCHAR(40), RECORD_KEY VARCHAR(40), USER_ID VARCHAR(10),
            LOG_TIMESTAMP VARCHAR(40)
          );
          CREATE TABLE IF NOT EXISTS AUDIT_LOG_ARCHIVE_T (
            LOG_ID BIGINT, PROGRAM_NAME VARCHAR(10), ACTION_CODE VARCHAR(3),
            TABLE_NAME VARCHAR(40), RECORD_KEY VARCHAR(40), USER_ID VARCHAR(10),
            LOG_TIMESTAMP VARCHAR(40), ARCHIVE_DATE DATE
          );
          CREATE TABLE IF NOT EXISTS DEDUCTIBLE_T (
            POLICY_ID VARCHAR(16), DEDUCTIBLE_AMT NUMERIC(11,2)
          );
          CREATE TABLE IF NOT EXISTS POLICY_T (
            POLICY_ID VARCHAR(16) PRIMARY KEY, STATUS CHAR(1), EXPIRY_DATE DATE,
            PREMIUM_DUE_DATE DATE, GRACE_DAYS INT
          );
          CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
            RUN_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
            PROGRAM_NAME VARCHAR(10), STATUS VARCHAR(20), ROWS_PROCESSED INT,
            RUN_STARTED TIMESTAMP, RUN_ENDED TIMESTAMP
          );
          """);
    }
  }

  @Test
  void loadRulesFromFileAndValidateDeny() throws Exception {
    Path yaml = temp.resolve("rules.yaml");
    Files.writeString(
        yaml,
        Files.readString(
            Path.of("src/test/resources/golden/normalization-rules.yaml")));
    NormalizationRules fromFile = NormalizationRules.load(yaml);
    assertEquals("2024-06-15", fromFile.defaultReferenceDate());
    assertTrue(fromFile.isTimestampColumn("CREATED_AT"));
    assertTrue(fromFile.isSurrogateColumn("PAYMENT_ID"));
    assertTrue(fromFile.isDenied("PAYMENT_AMT"));
    assertFalse(fromFile.isAllowedNormalizeColumn("PAYMENT_AMT"));
    assertThrows(
        ConfigurationException.class,
        () -> NormalizationRules.load(temp.resolve("missing.yaml")));
    assertThrows(
        ConfigurationException.class,
        () -> NormalizationRules.loadFromClasspath("no-such-resource.yaml"));
  }

  @Test
  void defaultTablesForAllPrograms() {
    for (String prog :
        List.of("BIL003B", "CLM006B", "AUD002B", "CMM001B", "POL006B", "PRM005B")) {
      List<TableDefinition> tables = GoldenOutputCapture.defaultTablesFor(prog);
      assertFalse(tables.isEmpty());
      assertTrue(tables.stream().anyMatch(t -> t.tableName().equals("RPT_RUN_LOG_T")));
    }
    assertThrows(
        ConfigurationException.class, () -> GoldenOutputCapture.defaultTablesFor("UNKNOWN"));
  }

  @Test
  void captureClaimPaymentNormalizesSurrogateNotMoney() throws Exception {
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute(
          "INSERT INTO CLAIM_RESERVE_T VALUES ('CLM1','RSV1','AP',1500.00,5000.00)");
      st.execute(
          "INSERT INTO CLAIM_PAYMENT_T (CLAIM_ID, PAYMENT_AMT, CREATED_AT) "
              + "VALUES ('CLM1', 1500.00, CURRENT_TIMESTAMP)");
      st.execute(
          "INSERT INTO RPT_RUN_LOG_T (PROGRAM_NAME, STATUS, ROWS_PROCESSED, RUN_STARTED, RUN_ENDED) "
              + "VALUES ('CLM006B','COMPLETED',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
    }
    GoldenOutputCapture capture = new GoldenOutputCapture(dataSource, context);
    GoldenArtifact artifact =
        capture.capture(
            "CLM006B",
            "scenario-01",
            GoldenOutputCapture.defaultTablesFor("CLM006B"),
            "ok",
            "COMPLETED");
    Path out = temp.resolve("clm.golden.json");
    capture.write(artifact, out);
    String json = Files.readString(out);
    assertTrue(json.contains("1500.00"));
    assertTrue(json.contains("SEQ_001"));
    assertTrue(json.contains("NORMALIZED_TS"));
    assertTrue(json.contains("AP") || json.contains("PD"));
  }

  @Test
  void captureCommissionAndAuditAndPolicyPaths() throws Exception {
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute(
          "INSERT INTO COMMISSION_T VALUES ('POL1','AGT1',1000.00,'Y',100.00)");
      st.execute(
          "INSERT INTO AUDIT_LOG_T VALUES (1,'CLM006B','PAY','CLAIM_PAYMENT_T','K1','U1','2023-01-01')");
      st.execute(
          "INSERT INTO AUDIT_LOG_ARCHIVE_T VALUES (1,'CLM006B','PAY','CLAIM_PAYMENT_T','K1','U1','2023-01-01','2024-06-15')");
      st.execute("INSERT INTO POLICY_T (POLICY_ID, STATUS, EXPIRY_DATE) VALUES ('POLREN1','A','2024-07-01')");
      st.execute("INSERT INTO DEDUCTIBLE_T VALUES ('POLREN1', 500.00)");
      st.execute(
          "INSERT INTO RPT_RUN_LOG_T (PROGRAM_NAME, STATUS, ROWS_PROCESSED, RUN_STARTED, RUN_ENDED) "
              + "VALUES ('CMM001B','COMPLETED',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
    }
    GoldenOutputCapture capture = new GoldenOutputCapture(dataSource, context);
    for (String prog : List.of("CMM001B", "AUD002B", "POL006B", "PRM005B")) {
      GoldenArtifact a =
          capture.capture(
              prog, "scenario-01", GoldenOutputCapture.defaultTablesFor(prog), "", "COMPLETED");
      assertEquals(prog, a.getProgram());
      assertTrue(capture.toCanonicalBytes(a).length > 10);
    }
  }

  @Test
  void artifactAccessorsAndCanonicalMap() {
    GoldenArtifact a = new GoldenArtifact();
    a.setFormatVersion("1.0.0");
    a.setProgram("X");
    a.setScenario("s");
    a.setReferenceDate("2024-06-15");
    a.setCompletionStatus("COMPLETED");
    a.setDisplayOutput("d");
    a.setRunLog(Map.of("status", "COMPLETED"));
    a.setTables(List.of(Map.of("tableName", "T", "rows", List.of())));
    assertEquals("1.0.0", a.getFormatVersion());
    assertEquals("X", a.getProgram());
    assertEquals("s", a.getScenario());
    assertEquals("2024-06-15", a.getReferenceDate());
    assertEquals("COMPLETED", a.getCompletionStatus());
    assertEquals("d", a.getDisplayOutput());
    assertFalse(a.getRunLog().isEmpty());
    assertEquals(1, a.getTables().size());
    assertTrue(a.toCanonicalMap().containsKey("tables"));
  }

  @Test
  void sequenceResetAndEmptySurrogate() {
    SequenceOrdinalNormalizer n = new SequenceOrdinalNormalizer();
    assertEquals("", n.normalize("ID", null));
    assertEquals("", n.normalize("ID", "NULL"));
    assertEquals("SEQ_001", n.normalize("ID", "9"));
    n.reset();
    assertEquals("SEQ_001", n.normalize("ID", "1"));
  }

  @Test
  void normalizeValueRejectsDeniedSqlType() {
    String money =
        context.normalizeValue("OTHER_AMT", "NUMERIC(11,2)", new BigDecimal("12.30"));
    assertEquals("12.30", money);
  }

  @Test
  void tableDefinitionRequiresBusinessKeys() {
    assertThrows(
        ConfigurationException.class,
        () -> new TableDefinition("T", List.of(), Map.of()).captureSql());
  }
}
