package com.pcis.golden;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.testcontainers.DockerClientFactory;
import org.testcontainers.containers.PostgreSQLContainer;

/**
 * Seeds billing data, applies a writer with a deliberate one-cent error, and verifies
 * {@link GoldenComparator} detects exactly the expected ONE_CENT_DIVERGENCE.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GoldenComparatorIntegrationTest {

  private static final String SCHEMA =
      """
      CREATE TABLE IF NOT EXISTS POLICY_T (
        POLICY_ID VARCHAR(16) PRIMARY KEY,
        BILLING_FREQ CHAR(1),
        ANNUAL_PREMIUM NUMERIC(11,2),
        STATUS CHAR(1)
      );
      CREATE TABLE IF NOT EXISTS BILLING_INSTALLMENT_T (
        INSTALLMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        POLICY_ID VARCHAR(16),
        INSTALLMENT_NO INT,
        AMOUNT NUMERIC(11,2)
      );
      CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
        RUN_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PROGRAM_NAME VARCHAR(10),
        STATUS VARCHAR(20),
        ROWS_PROCESSED INT,
        RUN_STARTED TIMESTAMP,
        RUN_ENDED TIMESTAMP
      );
      """;

  private DataSource dataSource;
  private PostgreSQLContainer<?> postgres;
  private GoldenComparator comparator;

  @BeforeEach
  void setUp() throws Exception {
    Path goldenRoot = GoldenComparator.resolveGoldenRoot();
    comparator =
        new GoldenComparator(goldenRoot, NormalizationConfig.loadFromClasspath("normalization-rules.yaml"));

    boolean usingPostgres =
        "1".equals(System.getenv("PCIS_USE_TESTCONTAINERS")) && tryStartPostgres();
    if (!usingPostgres) {
      JdbcDataSource h2 = new JdbcDataSource();
      h2.setURL("jdbc:h2:mem:pcis_golden_cmp;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
      h2.setUser("sa");
      h2.setPassword("");
      dataSource = h2;
    }

    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      for (String stmt : SCHEMA.split(";")) {
        if (!stmt.isBlank()) {
          st.execute(stmt);
        }
      }
    }
    resetAndSeed();
  }

  @AfterEach
  void tearDown() {
    if (postgres != null) {
      postgres.stop();
      postgres = null;
    }
  }

  private boolean tryStartPostgres() {
    try {
      if (!DockerClientFactory.instance().isDockerAvailable()) {
        return false;
      }
      postgres =
          new PostgreSQLContainer<>("postgres:17-alpine")
              .withDatabaseName("pcis")
              .withUsername("pcis")
              .withPassword("pcis");
      postgres.start();
      org.postgresql.ds.PGSimpleDataSource pg = new org.postgresql.ds.PGSimpleDataSource();
      pg.setUrl(postgres.getJdbcUrl());
      pg.setUser(postgres.getUsername());
      pg.setPassword(postgres.getPassword());
      dataSource = pg;
      return true;
    } catch (Throwable t) {
      return false;
    }
  }

  private void resetAndSeed() throws Exception {
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute("DELETE FROM BILLING_INSTALLMENT_T");
      st.execute("DELETE FROM RPT_RUN_LOG_T");
      st.execute("DELETE FROM POLICY_T");
      st.execute(
          "INSERT INTO POLICY_T (POLICY_ID, BILLING_FREQ, ANNUAL_PREMIUM, STATUS) "
              + "VALUES ('POLBIL0001', 'M', 1200.00, 'A')");
    }
  }

  /** Mock writer matching bil003b/scenario-01 golden baseline. */
  private void mockBillingWriterExact() throws Exception {
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute("DELETE FROM BILLING_INSTALLMENT_T");
      st.execute("DELETE FROM RPT_RUN_LOG_T WHERE PROGRAM_NAME = 'BIL003B'");
      for (int i = 1; i <= 12; i++) {
        st.execute(
            "INSERT INTO BILLING_INSTALLMENT_T (POLICY_ID, INSTALLMENT_NO, AMOUNT) VALUES ("
                + "'POLBIL0001', "
                + i
                + ", 100.00)");
      }
      st.execute(
          "INSERT INTO RPT_RUN_LOG_T (PROGRAM_NAME, STATUS, ROWS_PROCESSED, RUN_STARTED, RUN_ENDED) "
              + "VALUES ('BIL003B', 'COMPLETED', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
    }
  }

  /** Mutated writer: installment 3 is one cent off. */
  private void mockBillingWriterOneCentOff() throws Exception {
    mockBillingWriterExact();
    try (Connection c = dataSource.getConnection();
        Statement st = c.createStatement()) {
      st.execute(
          "UPDATE BILLING_INSTALLMENT_T SET AMOUNT = 100.01 "
              + "WHERE POLICY_ID = 'POLBIL0001' AND INSTALLMENT_NO = 3");
    }
  }

  @Test
  void bil003bScenarioMatchesGoldenWhenExact() throws Exception {
    mockBillingWriterExact();
    GoldenDiff diff = comparator.compare("bil003b/scenario-01", dataSource);
    assertTrue(diff.isMatch(), () -> GoldenDiffTextWriter.render(diff));
  }

  @Test
  void detectsOneCentDivergenceAgainstBil003bGolden() throws Exception {
    mockBillingWriterOneCentOff();
    GoldenDiff diff = comparator.compare("bil003b/scenario-01", dataSource);
    assertFalse(diff.isMatch());
    assertEquals(1, diff.getTotalDiffCount());
    GoldenDiffEntry entry = diff.getEntries().get(0);
    assertEquals(DiffCategory.ONE_CENT_DIVERGENCE, entry.getCategory());
    assertEquals("BILLING_INSTALLMENT_T", entry.getTable());
    assertEquals("AMOUNT", entry.getColumn());
    assertEquals("100.00", entry.getExpectedValue());
    assertEquals("100.01", entry.getActualValue());
    assertEquals("+0.01", entry.getSignedDelta());
    assertEquals("POLBIL0001", entry.getBusinessKey().get("POLICY_ID"));
    assertEquals(3, entry.getBusinessKey().get("INSTALLMENT_NO"));
  }
}
