spring:
  application:
    name: pcis-observability-it
  main:
    banner-mode: "off"

pcis:
  observability:
    enabled: true
    trace-sample-rate: 0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: ping,livenessState
        readiness:
          include: readinessState
        startup:
          include: ping
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

otel:
  sdk:
    disabled: true
  metrics:
    exporter: none
  logs:
    exporter: none
  traces:
    exporter: none

logging:
  level:
    root: INFO
    com.pcis: DEBUG
