-- WO-195: batch run-log and exception tracking for policy renewal job

CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
    RUN_LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PGM_NAME VARCHAR(10) NOT NULL,
    RUN_DATE DATE NOT NULL,
    REC_SELECTED INTEGER NOT NULL DEFAULT 0,
    REC_UPDATED INTEGER NOT NULL DEFAULT 0,
    REC_ERRORS INTEGER NOT NULL DEFAULT 0,
    REC_DELINQUENT INTEGER,
    START_TIMESTAMP TIMESTAMP(6) NOT NULL,
    END_TIMESTAMP TIMESTAMP(6) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch_exceptions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL,
    policy_number VARCHAR(12),
    error_type VARCHAR(50) NOT NULL,
    error_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_batch_exceptions_job_execution
    ON batch_exceptions (job_execution_id);
