spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pcis_policy_dev
    username: pcis_policy_dev
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/pcis

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pcis.policy: DEBUG
    org.flywaydb.core: INFO
    org.hibernate.SQL: DEBUG
