-- Minimal AUDIT_LOG_T schema for PII scanner integration tests (WO-163)
CREATE TABLE AUDIT_LOG_T (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    PROGRAM_NAME VARCHAR(10),
    ACTION_CODE VARCHAR(10),
    TABLE_NAME VARCHAR(30),
    RECORD_KEY VARCHAR(40),
    USER_ID VARCHAR(10),
    OLD_VALUE VARCHAR(100),
    NEW_VALUE VARCHAR(100),
    LOG_TIMESTAMP TIMESTAMP,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (LOG_ID, CRT_TIMESTAMP)
);
