-- Billing domain reconciliation (WO-201)
-- Extends pcis-schema V1 baseline without conflicting V1 migration.

CREATE SEQUENCE IF NOT EXISTS seq_payment_id
    START WITH 10000000 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NO CYCLE CACHE 100;

ALTER TABLE BILLING_SCHEDULE_T
    ADD COLUMN IF NOT EXISTS REC_DELINQUENT INTEGER;

ALTER TABLE INVOICE_T
    ADD COLUMN IF NOT EXISTS POL_NBR VARCHAR(12);

ALTER TABLE PAYMENT_T
    ADD COLUMN IF NOT EXISTS PAYMENT_REF VARCHAR(12);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_t_payment_ref
    ON PAYMENT_T (PAYMENT_REF)
    WHERE PAYMENT_REF IS NOT NULL;

CREATE TABLE IF NOT EXISTS INVOICE_LINE_T (
    INVOICE_LINE_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID        BIGINT       NOT NULL,
    LINE_NBR          INTEGER      NOT NULL,
    LINE_DESC         VARCHAR(60),
    LINE_AMT          NUMERIC(11,2) NOT NULL,
    CRT_USER          VARCHAR(10),
    CRT_TIMESTAMP     TIMESTAMP,
    UPD_USER          VARCHAR(10),
    UPD_TIMESTAMP     TIMESTAMP,
    PRIMARY KEY (INVOICE_LINE_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT_APPLICATION_T (
    PAYMENT_APP_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    PAYMENT_ID     BIGINT       NOT NULL,
    INVOICE_ID     BIGINT       NOT NULL,
    APPLIED_AMT    NUMERIC(11,2) NOT NULL,
    CRT_USER       VARCHAR(10),
    CRT_TIMESTAMP  TIMESTAMP,
    UPD_USER       VARCHAR(10),
    UPD_TIMESTAMP  TIMESTAMP,
    PRIMARY KEY (PAYMENT_APP_ID)
);

CREATE INDEX IF NOT EXISTS idx_invoice_line_invoice_id ON INVOICE_LINE_T (INVOICE_ID);
CREATE INDEX IF NOT EXISTS idx_payment_application_payment_id ON PAYMENT_APPLICATION_T (PAYMENT_ID);
CREATE INDEX IF NOT EXISTS idx_payment_application_invoice_id ON PAYMENT_APPLICATION_T (INVOICE_ID);
CREATE INDEX IF NOT EXISTS idx_invoice_t_pol_nbr ON INVOICE_T (POL_NBR);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_invoice_line_t_invoice_id'
    ) THEN
        ALTER TABLE INVOICE_LINE_T
            ADD CONSTRAINT fk_invoice_line_t_invoice_id
            FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE_T (INVOICE_ID);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_application_t_payment_id'
    ) THEN
        ALTER TABLE PAYMENT_APPLICATION_T
            ADD CONSTRAINT fk_payment_application_t_payment_id
            FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT_T (PAYMENT_ID);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_application_t_invoice_id'
    ) THEN
        ALTER TABLE PAYMENT_APPLICATION_T
            ADD CONSTRAINT fk_payment_application_t_invoice_id
            FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE_T (INVOICE_ID);
    END IF;
END $$;
