-- Payment application enhancements (WO-203)

ALTER TABLE PAYMENT_T
    ALTER COLUMN PAYMENT_REF TYPE VARCHAR(14);

ALTER TABLE PAYMENT_T
    ADD COLUMN IF NOT EXISTS POL_NBR VARCHAR(12);

ALTER TABLE PAYMENT_T
    ADD COLUMN IF NOT EXISTS PAYMENT_METHOD CHAR(2);

ALTER TABLE PAYMENT_APPLICATION_T
    ADD COLUMN IF NOT EXISTS APPLIED_DATE DATE;

ALTER TABLE BILLING_SCHEDULE_T
    ADD COLUMN IF NOT EXISTS VERSION BIGINT NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_t_payment_token
    ON PAYMENT_T (PAYMENT_TOKEN)
    WHERE PAYMENT_TOKEN IS NOT NULL;
