-- PII scan fixtures: masked rows plus one intentionally unmasked row per pattern type (WO-163)
DELETE FROM AUDIT_LOG_T;

INSERT INTO AUDIT_LOG_T (
    PROGRAM_NAME, ACTION_CODE, TABLE_NAME, RECORD_KEY, USER_ID,
    OLD_VALUE, NEW_VALUE, LOG_TIMESTAMP, CRT_USER, CRT_TIMESTAMP)
VALUES
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', 'CUST000001', 'CSR1',
     '***-**-6789', '***-**-6790', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', 'CUST000002', 'CSR1',
     '***@example.com', '***@example.com', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', 'CUST000003', 'CSR1',
     '***-***-6789', '***-***-6790', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', '1HGCM82633A004352', 'CSR1',
     '[REDACTED]', '[REDACTED]', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', 'CUST000005', 'CSR1',
     '123456789', '123456789', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
    ('AUDLOG01', 'UPD', 'CUSTOMER_T', 'CUST000006', 'CSR1',
     '123-45-6789', '123-45-6789', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
