-- WO-233: Reporting integration test fixtures.
CREATE TABLE IF NOT EXISTS POLICY_T (
    POL_NBR VARCHAR(12) PRIMARY KEY,
    POL_TYPE VARCHAR(3) NOT NULL,
    POL_STATUS CHAR(1) NOT NULL,
    PREM_ANNUAL NUMERIC(11, 2) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS BILLING_SCHEDULE_T (
    SCHEDULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POL_NBR VARCHAR(12) NOT NULL,
    DUE_DATE DATE NOT NULL,
    AMOUNT_DUE NUMERIC(9, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS CLAIM_RESERVE_T (
    RESERVE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLM_NBR VARCHAR(12) NOT NULL,
    RESERVE_AMT NUMERIC(11, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS RPT_RUN_LOG_T (
    RUN_LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PGM_NAME VARCHAR(10) NOT NULL,
    RUN_DATE DATE NOT NULL,
    REC_SELECTED INTEGER NOT NULL DEFAULT 0,
    REC_UPDATED INTEGER NOT NULL DEFAULT 0,
    REC_ERRORS INTEGER NOT NULL DEFAULT 0,
    REC_DELINQUENT INTEGER,
    START_TIMESTAMP TIMESTAMP(6) NOT NULL,
    END_TIMESTAMP TIMESTAMP(6) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);
INSERT INTO POLICY_T (POL_NBR, POL_TYPE, POL_STATUS, PREM_ANNUAL) VALUES
    ('POL000000001', 'HOM', 'A', 1250.00),
    ('POL000000002', 'CML', 'A', 8900.50),
    ('POL000000003', 'AUT', 'E', 640.25);
INSERT INTO BILLING_SCHEDULE_T (POL_NBR, DUE_DATE, AMOUNT_DUE) VALUES
    ('POL000000001', DATE '2026-01-15', 104.17),
    ('POL000000002', DATE '2026-01-01', 741.71);
INSERT INTO CLAIM_RESERVE_T (CLM_NBR, RESERVE_AMT) VALUES
    ('CLM000000001', 15000.00);
INSERT INTO RPT_RUN_LOG_T (PGM_NAME, RUN_DATE, REC_SELECTED, REC_UPDATED, REC_ERRORS, START_TIMESTAMP, END_TIMESTAMP, CRT_USER)
VALUES ('RPT001A', DATE '2026-01-31', 1200, 0, 0, TIMESTAMP '2026-01-31 02:00:00', TIMESTAMP '2026-01-31 02:05:12', 'BATCH');
