-- WO-172: CONFIG_TUNABLE_T schema and seed data

CREATE TABLE CONFIG_TUNABLE_T (
    TUNABLE_KEY VARCHAR(60) PRIMARY KEY,
    DOMAIN_CD CHAR(3) NOT NULL,
    VALUE_TYPE CHAR(1) NOT NULL,
    VALUE_TEXT VARCHAR(200),
    NUMERIC_VALUE DECIMAL(11,2),
    MIN_VALUE DECIMAL(11,2),
    MAX_VALUE DECIMAL(11,2),
    UNIT_CD VARCHAR(10),
    DESCRIPTION VARCHAR(200) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    VERSION_NO INTEGER NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP
);

CREATE TABLE CONFIG_TUNABLE_HISTORY_T (
    HISTORY_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TUNABLE_KEY VARCHAR(60) NOT NULL,
    VERSION_NO INTEGER NOT NULL,
    OLD_VALUE VARCHAR(200),
    NEW_VALUE VARCHAR(200) NOT NULL,
    CHANGE_REASON VARCHAR(200) NOT NULL,
    CHANGED_BY VARCHAR(50) NOT NULL,
    CHANGED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION config_tunable_history_immutable()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'CONFIG_TUNABLE_HISTORY_T is append-only';
END;
$$;

CREATE TRIGGER trg_config_tunable_history_immutable
    BEFORE UPDATE OR DELETE ON CONFIG_TUNABLE_HISTORY_T
    FOR EACH ROW EXECUTE FUNCTION config_tunable_history_immutable();

INSERT INTO CONFIG_TUNABLE_T (
    TUNABLE_KEY, DOMAIN_CD, VALUE_TYPE, NUMERIC_VALUE, MIN_VALUE, MAX_VALUE,
    UNIT_CD, DESCRIPTION, EFFECTIVE_FROM, VERSION_NO, CRT_USER, CRT_TIMESTAMP
) VALUES
    ('audit.retention.days', 'AUD', 'I', 365, 365, 3650, 'days', 'Audit retention period', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP),
    ('audit.archive.chunkSize', 'AUD', 'I', 1000, 100, 5000, 'rows', 'Audit archive chunk size', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP),
    ('billing.leadDays', 'BIL', 'I', 15, 1, 90, 'days', 'Billing lead days', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP),
    ('premium.graceDays', 'PRM', 'I', 10, 0, 60, 'days', 'Premium grace days', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP),
    ('policy.renewalWindowDays', 'POL', 'I', 60, 1, 180, 'days', 'Policy renewal window', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP),
    ('claims.reinsurance.cessionThreshold', 'CLM', 'M', 100000.00, 0, 9999999.99, 'USD', 'Reinsurance cession threshold', CURRENT_DATE, 1, 'SYSTEM', CURRENT_TIMESTAMP);
