-- COMM_CALC_FLAG = Y → skip (already commissioned)
INSERT INTO COMMISSION_T (POLICY_ID, AGENT_ID, PREMIUM_AMT, COMM_CALC_FLAG, COMMISSION_AMT) VALUES
 ('POLCMM0002', 'AGT002', 2000.00, 'Y', 200.00);
