replicaCount: 1
autoscaling:
  enabled: true
  enableHpa: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  enablePdb: true
  minAvailable: 1
ingress:
  enabled: true
  host: pcis-api-gateway-dev.agent.opsera.dev
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
env:
  SPRING_PROFILES_ACTIVE: dev
  KEYCLOAK_ISSUER_URI: https://pcis-dev.agent.opsera.dev/realms/pcis
  KEYCLOAK_JWK_SET_URI: http://keycloak.pcis-dev.svc.cluster.local/realms/pcis/protocol/openid-connect/certs
  PCIS_REDIS_HOST: redis.pcis-dev.svc.cluster.local
  PCIS_REDIS_PORT: '6379'
istio:
  inject: false
probes:
  startup:
    failureThreshold: 60
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 20
    periodSeconds: 10
image:
  repository: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/pcis-api-gateway
  tag: dev-1e67a50-20260812191202-amd64
  pullPolicy: Always
