# Default values for pcis-platform (override with values-dev.yaml for EKS dev).

namespace: pcis-dev

postgresql:
  enabled: true
  image: postgres:17-alpine
  serviceName: postgresql
  port: 5432
  superuser:
    username: postgres
    password: postgres
  appUser:
    username: pcis
    password: pcis
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

redis:
  enabled: true
  image: redis:7-alpine
  serviceName: redis
  port: 6379
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

keycloak:
  enabled: true
  image: quay.io/keycloak/keycloak:26.0.2
  serviceName: keycloak
  port: 8080
  managementPort: 9000
  admin:
    username: admin
    password: admin
  db:
    image: postgres:16-alpine
    database: keycloak
    username: keycloak
    password: keycloak_local_only
    persistence:
      enabled: true
      size: 5Gi
  realmImport:
    enabled: true
    filename: pcis-realm.json
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

kafka:
  enabled: false
  image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
  serviceName: kafka
  port: 9092
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
