replicaCount: 1
autoscaling:
  enabled: true
  enableHpa: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  enablePdb: true
  minAvailable: 1
ingress:
  enabled: false
  host: ''
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.pcis-dev.svc.cluster.local:5432/pcis_claims
  SPRING_DATASOURCE_USERNAME: pcis
  SPRING_DATASOURCE_PASSWORD: pcis
  DATASOURCE_URL: jdbc:postgresql://postgresql.pcis-dev.svc.cluster.local:5432/pcis_claims
  DATASOURCE_USERNAME: pcis
  DATASOURCE_PASSWORD: pcis
  KEYCLOAK_ISSUER_URI: http://keycloak.pcis-dev.svc.cluster.local/realms/pcis
  KEYCLOAK_JWK_SET_URI: http://keycloak.pcis-dev.svc.cluster.local/realms/pcis/protocol/openid-connect/certs
image:
  repository: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/pcis-claims-svc
  tag: dev-1e67a50-20260812191201-amd64
  pullPolicy: Always
