-- V6: claim authority reference tables for payment authorization checks (read-only in authz-svc)

CREATE TABLE CLAIM_T (
    CLAIM_ID VARCHAR(12) NOT NULL,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CLAIM_ID)
);

CREATE TABLE CLAIM_ADJUSTER_T (
    ADJUSTER_ID VARCHAR(10) NOT NULL,
    ADJ_NAME VARCHAR(60),
    AUTHORITY_LIMIT NUMERIC(13,2) NOT NULL,
    ADJ_STATUS VARCHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ADJUSTER_ID)
);

CREATE TABLE CLAIM_RESERVE_T (
    RESERVE_HIST_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12) NOT NULL,
    RESERVE_AMT NUMERIC(13,2) NOT NULL,
    CHANGE_REASON VARCHAR(60),
    RESERVE_STATUS VARCHAR(2),
    PAID_TO_DATE NUMERIC(13,2) NOT NULL DEFAULT 0.00,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (RESERVE_HIST_ID),
    CONSTRAINT fk_claim_reserve_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID)
);

CREATE TABLE APPROVAL_T (
    APPROVAL_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    APPROVER_ID VARCHAR(10),
    APPROVED_AMT NUMERIC(13,2),
    APPROVAL_STATUS VARCHAR(10),
    APPROVAL_DATE DATE,
    RESERVE_HIST_ID BIGINT,
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT fk_approval_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID),
    CONSTRAINT fk_approval_t_reserve_hist_id FOREIGN KEY (RESERVE_HIST_ID) REFERENCES CLAIM_RESERVE_T (RESERVE_HIST_ID),
    CONSTRAINT fk_approval_t_approver_id FOREIGN KEY (APPROVER_ID) REFERENCES CLAIM_ADJUSTER_T (ADJUSTER_ID),
    CONSTRAINT chk_approval_status CHECK (APPROVAL_STATUS IN ('REQUESTED','APPROVED','DENIED','PENDING','CONSUMED','EXPIRED'))
);

CREATE TABLE CLAIM_PAYMENT_T (
    PAYMENT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CLAIM_ID VARCHAR(12),
    ADJUSTER_ID VARCHAR(10),
    PAYMENT_AMT NUMERIC(11,2),
    PAYMENT_DATE DATE,
    PAYEE_NAME VARCHAR(60),
    PAYMENT_STATUS VARCHAR(4),
    CRT_USER VARCHAR(10),
    CRT_TIMESTAMP TIMESTAMP,
    UPD_USER VARCHAR(10),
    UPD_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT fk_claim_payment_t_claim_id FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM_T (CLAIM_ID),
    CONSTRAINT fk_claim_payment_t_adjuster_id FOREIGN KEY (ADJUSTER_ID) REFERENCES CLAIM_ADJUSTER_T (ADJUSTER_ID)
);

CREATE INDEX idx_approval_claim_reserve ON APPROVAL_T (CLAIM_ID, RESERVE_HIST_ID, APPROVAL_STATUS);
CREATE INDEX idx_claim_payment_claim_adjuster ON CLAIM_PAYMENT_T (CLAIM_ID, ADJUSTER_ID);
