-- WO-238: Measure production table volumes in INSPRDDTA.
-- Returns row count and CRT_TIMESTAMP range for all 55 PCIS tables.
-- Source inventory: docs/data-dictionary.yaml, PCIS_Database_Design.md
-- Run on Db2 for i production (read-only); expect elevated I/O on large tables.

SELECT
    'CUSTOMER_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CUSTOMER_T
UNION ALL
SELECT
    'CUSTOMER_ADDRESS_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CUSTOMER_ADDRESS_T
UNION ALL
SELECT
    'CUSTOMER_CONTACT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CUSTOMER_CONTACT_T
UNION ALL
SELECT
    'AGENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.AGENT_T
UNION ALL
SELECT
    'AGENT_LICENSE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.AGENT_LICENSE_T
UNION ALL
SELECT
    'AGENT_COMMISSION_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.AGENT_COMMISSION_T
UNION ALL
SELECT
    'COMMISSION_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.COMMISSION_T
UNION ALL
SELECT
    'COMMISSION_RATE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.COMMISSION_RATE_T
UNION ALL
SELECT
    'QUOTE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.QUOTE_T
UNION ALL
SELECT
    'QUOTE_COVERAGE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.QUOTE_COVERAGE_T
UNION ALL
SELECT
    'UW_RULE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.UW_RULE_T
UNION ALL
SELECT
    'UW_REFERRAL_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.UW_REFERRAL_T
UNION ALL
SELECT
    'UW_DECISION_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.UW_DECISION_T
UNION ALL
SELECT
    'POLICY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.POLICY_T
UNION ALL
SELECT
    'COVERAGE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.COVERAGE_T
UNION ALL
SELECT
    'COVERAGE_TYPE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.COVERAGE_TYPE_T
UNION ALL
SELECT
    'DEDUCTIBLE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.DEDUCTIBLE_T
UNION ALL
SELECT
    'POLICY_HISTORY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.POLICY_HISTORY_T
UNION ALL
SELECT
    'POLICY_VEHICLE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.POLICY_VEHICLE_T
UNION ALL
SELECT
    'POLICY_PROPERTY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.POLICY_PROPERTY_T
UNION ALL
SELECT
    'ENDORSEMENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.ENDORSEMENT_T
UNION ALL
SELECT
    'CANCELLATION_REASON_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CANCELLATION_REASON_T
UNION ALL
SELECT
    'RATE_TABLE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RATE_TABLE_T
UNION ALL
SELECT
    'RATE_FACTOR_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RATE_FACTOR_T
UNION ALL
SELECT
    'PREMIUM_CALC_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.PREMIUM_CALC_T
UNION ALL
SELECT
    'PREMIUM_CALC_DETAIL_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.PREMIUM_CALC_DETAIL_T
UNION ALL
SELECT
    'DISCOUNT_RULE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.DISCOUNT_RULE_T
UNION ALL
SELECT
    'SURCHARGE_RULE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.SURCHARGE_RULE_T
UNION ALL
SELECT
    'TAX_TABLE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.TAX_TABLE_T
UNION ALL
SELECT
    'RISK_SCORE_FACTOR_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RISK_SCORE_FACTOR_T
UNION ALL
SELECT
    'BILLING_PLAN_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.BILLING_PLAN_T
UNION ALL
SELECT
    'BILLING_SCHEDULE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.BILLING_SCHEDULE_T
UNION ALL
SELECT
    'BILLING_NOTICE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.BILLING_NOTICE_T
UNION ALL
SELECT
    'INVOICE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.INVOICE_T
UNION ALL
SELECT
    'PAYMENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.PAYMENT_T
UNION ALL
SELECT
    'REFUND_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.REFUND_T
UNION ALL
SELECT
    'CLAIM_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_T
UNION ALL
SELECT
    'CLAIM_RESERVE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_RESERVE_T
UNION ALL
SELECT
    'CLAIM_RESERVE_HISTORY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_RESERVE_HISTORY_T
UNION ALL
SELECT
    'CLAIM_PAYMENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_PAYMENT_T
UNION ALL
SELECT
    'CLAIM_ADJUSTER_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_ADJUSTER_T
UNION ALL
SELECT
    'CLAIM_NOTE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_NOTE_T
UNION ALL
SELECT
    'CLAIM_DOCUMENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CLAIM_DOCUMENT_T
UNION ALL
SELECT
    'APPROVAL_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.APPROVAL_T
UNION ALL
SELECT
    'RECOVERY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RECOVERY_T
UNION ALL
SELECT
    'REINSURANCE_TREATY_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.REINSURANCE_TREATY_T
UNION ALL
SELECT
    'REINSURANCE_CESSION_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.REINSURANCE_CESSION_T
UNION ALL
SELECT
    'DOCUMENT_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.DOCUMENT_T
UNION ALL
SELECT
    'RPT_RUN_LOG_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RPT_RUN_LOG_T
UNION ALL
SELECT
    'RPT_PARM_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.RPT_PARM_T
UNION ALL
SELECT
    'AUDIT_LOG_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.AUDIT_LOG_T
UNION ALL
SELECT
    'AUDIT_LOG_ARCHIVE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.AUDIT_LOG_ARCHIVE_T
UNION ALL
SELECT
    'SEC_USER_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.SEC_USER_T
UNION ALL
SELECT
    'ROLE_MENU_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.ROLE_MENU_T
UNION ALL
SELECT
    'CODE_TABLE_T' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    MIN(CRT_TIMESTAMP) AS MIN_CRT_TIMESTAMP,
    MAX(CRT_TIMESTAMP) AS MAX_CRT_TIMESTAMP
FROM INSPRDDTA.CODE_TABLE_T
ORDER BY TABLE_NAME;
