-- WO-238: Measure 30-day batch-window baseline from RPT_RUN_LOG_T (WO-237 timing).
-- Uses START_TIMESTAMP / END_TIMESTAMP wall-clock columns for duration statistics.
-- Run against INSPRDDTA on Db2 for i production after instrumented batch runs exist.

WITH RUNS AS (
    SELECT
        PGM_NAME,
        RUN_DATE,
        START_TIMESTAMP,
        END_TIMESTAMP,
        TIMESTAMPDIFF(2, CHAR(END_TIMESTAMP - START_TIMESTAMP)) AS DURATION_SECONDS,
        REC_SELECTED,
        REC_UPDATED,
        REC_ERRORS,
        REC_DELINQUENT
    FROM INSPRDDTA.RPT_RUN_LOG_T
    WHERE PGM_NAME IN (
        'AUD002B',
        'BIL003B',
        'CLM006B',
        'CMM001B',
        'POL006B',
        'PRM005B'
    )
      AND START_TIMESTAMP >= CURRENT TIMESTAMP - 30 DAYS
),
PER_PROGRAM AS (
    SELECT
        PGM_NAME,
        COUNT(*) AS RUN_COUNT,
        AVG(DURATION_SECONDS) AS AVG_DURATION_SECONDS,
        MAX(DURATION_SECONDS) AS MAX_DURATION_SECONDS,
        MIN(DURATION_SECONDS) AS MIN_DURATION_SECONDS,
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY DURATION_SECONDS)
            AS P95_DURATION_SECONDS,
        SUM(REC_SELECTED) AS TOTAL_REC_SELECTED,
        SUM(REC_UPDATED) AS TOTAL_REC_UPDATED,
        SUM(REC_ERRORS) AS TOTAL_REC_ERRORS,
        AVG(REC_SELECTED) AS AVG_REC_SELECTED,
        AVG(REC_UPDATED) AS AVG_REC_UPDATED,
        AVG(REC_ERRORS) AS AVG_REC_ERRORS,
        MAX(REC_ERRORS) AS MAX_REC_ERRORS_PER_RUN
    FROM RUNS
    GROUP BY PGM_NAME
)
SELECT
    PGM_NAME,
    RUN_COUNT,
    AVG_DURATION_SECONDS,
    MAX_DURATION_SECONDS,
    MIN_DURATION_SECONDS,
    P95_DURATION_SECONDS,
    AVG_REC_SELECTED,
    AVG_REC_UPDATED,
    AVG_REC_ERRORS,
    TOTAL_REC_SELECTED,
    TOTAL_REC_UPDATED,
    TOTAL_REC_ERRORS,
    MAX_REC_ERRORS_PER_RUN
FROM PER_PROGRAM
ORDER BY PGM_NAME;
